(* Load-fidelity test for 100/konigsberg.ml (translated by tools/translator). Keep
   in sync with 100/konigsberg/konigsberg_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
start_trace ();;
#use "100/konigsberg.ml";;
show_trace "100/konigsberg";;
(* BEGIN generated theorem list *)
attempt "edges" (fun () -> sthm edges);;
attempt "vertices" (fun () -> sthm vertices);;
attempt "termini" (fun () -> sthm termini);;
attempt "graph" (fun () -> sthm graph);;
attempt "TERMINI_IN_VERTICES" (fun () -> sthm TERMINI_IN_VERTICES);;
attempt "connects" (fun () -> sthm connects);;
attempt "delete_edge" (fun () -> sthm delete_edge);;
attempt "DELETE_EDGE_CLAUSES" (fun () -> sthm DELETE_EDGE_CLAUSES);;
attempt "GRAPH_DELETE_EDGE" (fun () -> sthm GRAPH_DELETE_EDGE);;
attempt "locally_finite" (fun () -> sthm locally_finite);;
attempt "localdegree" (fun () -> sthm localdegree);;
attempt "degree" (fun () -> sthm degree);;
attempt "DEGREE_DELETE_EDGE" (fun () -> sthm DEGREE_DELETE_EDGE);;
attempt "eulerian_RULES" (fun () -> sthm eulerian_RULES);;
attempt "eulerian_INDUCT" (fun () -> sthm eulerian_INDUCT);;
attempt "eulerian_CASES" (fun () -> sthm eulerian_CASES);;
attempt "EULERIAN_FINITE" (fun () -> sthm EULERIAN_FINITE);;
attempt "EULERIAN_ODD_LEMMA" (fun () -> sthm EULERIAN_ODD_LEMMA);;
attempt "EULERIAN_ODD" (fun () -> sthm EULERIAN_ODD);;
attempt "KOENIGSBERG" (fun () -> sthm KOENIGSBERG);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
