(* Load-fidelity test for 100/primerecip.ml (translated by tools/translator). Keep
   in sync with 100/primerecip/primerecip_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "Library/prime.ml";;
#use "Library/iter.ml";;
#use "Library/pocklington.ml";;
#use "Library/analysis.ml";;
#use "Library/transc.ml";;
#use "Library/calc_real.ml";;
#use "Library/floor.ml";;
#use "100/bertrand.ml";;
#use "100/divharmonic.ml";;
start_trace ();;
#use "100/primerecip.ml";;
show_trace "100/primerecip";;
(* BEGIN generated theorem list *)
attempt "INDUCTION_FROM_1" (fun () -> sthm INDUCTION_FROM_1);;
attempt "PRIMERECIP_HARMONIC_LBOUND" (fun () -> sthm PRIMERECIP_HARMONIC_LBOUND);;
attempt "PRIMERECIP_LBOUND" (fun () -> sthm PRIMERECIP_LBOUND);;
attempt "UNBOUNDED_DIVERGENT" (fun () -> sthm UNBOUNDED_DIVERGENT);;
attempt "PRIMERECIP_DIVERGES_NUMSEG" (fun () -> sthm PRIMERECIP_DIVERGES_NUMSEG);;
attempt "PRIMERECIP_DIVERGES" (fun () -> sthm PRIMERECIP_DIVERGES);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
