(* Load-fidelity test for 100/perfect.ml (translated by tools/translator). Keep
   in sync with 100/perfect/perfect_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "Library/prime.ml";;
start_trace ();;
#use "100/perfect.ml";;
show_trace "100/perfect";;
(* BEGIN generated theorem list *)
attempt "sigma" (fun () -> sthm sigma);;
attempt "perfect" (fun () -> sthm perfect);;
attempt "ODD_POW2_MINUS1" (fun () -> sthm ODD_POW2_MINUS1);;
attempt "EVEN_ODD_DECOMP" (fun () -> sthm EVEN_ODD_DECOMP);;
attempt "FINITE_DIVISORS" (fun () -> sthm FINITE_DIVISORS);;
attempt "MULT_EQ_COPRIME" (fun () -> sthm MULT_EQ_COPRIME);;
attempt "COPRIME_ODD_POW2" (fun () -> sthm COPRIME_ODD_POW2);;
attempt "MULT_NSUM" (fun () -> sthm MULT_NSUM);;
attempt "SIGMA_0" (fun () -> sthm SIGMA_0);;
attempt "SIGMA_1" (fun () -> sthm SIGMA_1);;
attempt "SIGMA_LBOUND" (fun () -> sthm SIGMA_LBOUND);;
attempt "SIGMA_MULT" (fun () -> sthm SIGMA_MULT);;
attempt "SIGMA_PRIME" (fun () -> sthm SIGMA_PRIME);;
attempt "SIGMA_PRIME_EQ" (fun () -> sthm SIGMA_PRIME_EQ);;
attempt "SIGMA_POW2" (fun () -> sthm SIGMA_POW2);;
attempt "SIGMA_MULTIPLICATIVE" (fun () -> sthm SIGMA_MULTIPLICATIVE);;
attempt "PERFECT_EUCLID" (fun () -> sthm PERFECT_EUCLID);;
attempt "PERFECT_EULER" (fun () -> sthm PERFECT_EULER);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
