(* Load-fidelity test for 100/two_squares.ml (translated by tools/translator). Keep
   in sync with 100/two_squares/two_squares_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "Library/prime.ml";;
start_trace ();;
#use "100/two_squares.ml";;
show_trace "100/two_squares";;
(* BEGIN generated theorem list *)
attempt "involution" (fun () -> sthm involution);;
attempt "INVOLUTION_IMAGE" (fun () -> sthm INVOLUTION_IMAGE);;
attempt "INVOLUTION_DELETE" (fun () -> sthm INVOLUTION_DELETE);;
attempt "INVOLUTION_STEPDOWN" (fun () -> sthm INVOLUTION_STEPDOWN);;
attempt "INVOLUTION_NOFIXES" (fun () -> sthm INVOLUTION_NOFIXES);;
attempt "INVOLUTION_SUBSET" (fun () -> sthm INVOLUTION_SUBSET);;
attempt "INVOLUTION_EVEN" (fun () -> sthm INVOLUTION_EVEN);;
attempt "INVOLUTION_FIX_ODD" (fun () -> sthm INVOLUTION_FIX_ODD);;
attempt "INVOLUTION_ODD" (fun () -> sthm INVOLUTION_ODD);;
attempt "INVOLUTION_FIX_FIX" (fun () -> sthm INVOLUTION_FIX_FIX);;
attempt "zset" (fun () -> sthm zset);;
attempt "zag" (fun () -> sthm zag);;
attempt "tag" (fun () -> sthm tag);;
attempt "ZAG_INVOLUTION_GENERAL" (fun () -> sthm ZAG_INVOLUTION_GENERAL);;
attempt "IN_TRIPLE" (fun () -> sthm IN_TRIPLE);;
attempt "PRIME_SQUARE" (fun () -> sthm PRIME_SQUARE);;
attempt "PRIME_4X" (fun () -> sthm PRIME_4X);;
attempt "PRIME_XYZ_NONZERO" (fun () -> sthm PRIME_XYZ_NONZERO);;
attempt "ZAG_INVOLUTION" (fun () -> sthm ZAG_INVOLUTION);;
attempt "TAG_INVOLUTION" (fun () -> sthm TAG_INVOLUTION);;
attempt "ZAG_LEMMA" (fun () -> sthm ZAG_LEMMA);;
attempt "ZSET_BOUND" (fun () -> sthm ZSET_BOUND);;
attempt "ZSET_FINITE" (fun () -> sthm ZSET_FINITE);;
attempt "SUM_OF_TWO_SQUARES" (fun () -> sthm SUM_OF_TWO_SQUARES);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
