(* Load-fidelity test for 100/friendship.ml (translated by tools/translator). Keep
   in sync with 100/friendship/friendship_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "Library/prime.ml";;
#use "Library/iter.ml";;
#use "Library/pocklington.ml";;
start_trace ();;
#use "100/friendship.ml";;
show_trace "100/friendship";;
(* BEGIN generated theorem list *)
attempt "GCD_INDUCT" (fun () -> sthm GCD_INDUCT);;
attempt "LOOP_GCD" (fun () -> sthm LOOP_GCD);;
attempt "LOOP_COPRIME" (fun () -> sthm LOOP_COPRIME);;
attempt "EQUIVALENCE_UNIFORM_PARTITION" (fun () -> sthm EQUIVALENCE_UNIFORM_PARTITION);;
attempt "EQUIVALENCE_UNIFORM_PARTITION_RESTRICT" (fun () -> sthm EQUIVALENCE_UNIFORM_PARTITION_RESTRICT);;
attempt "ELEMENTS_PAIR_UP" (fun () -> sthm ELEMENTS_PAIR_UP);;
attempt "cycle" (fun () -> sthm cycle);;
attempt "path" (fun () -> sthm path);;
attempt "CYCLE_OFFSET" (fun () -> sthm CYCLE_OFFSET);;
attempt "CYCLE_MOD" (fun () -> sthm CYCLE_MOD);;
attempt "PATHS_MONO" (fun () -> sthm PATHS_MONO);;
attempt "HAS_SIZE_PATHS" (fun () -> sthm HAS_SIZE_PATHS);;
attempt "FINITE_PATHS" (fun () -> sthm FINITE_PATHS);;
attempt "HAS_SIZE_CYCLES" (fun () -> sthm HAS_SIZE_CYCLES);;
attempt "FINITE_CYCLES" (fun () -> sthm FINITE_CYCLES);;
attempt "CARD_PATHCYCLES_STEP" (fun () -> sthm CARD_PATHCYCLES_STEP);;
attempt "shiftable" (fun () -> sthm shiftable);;
attempt "SHIFTABLE_REFL" (fun () -> sthm SHIFTABLE_REFL);;
attempt "SHIFTABLE_TRANS" (fun () -> sthm SHIFTABLE_TRANS);;
attempt "SHIFTABLE_LOCAL" (fun () -> sthm SHIFTABLE_LOCAL);;
attempt "SHIFTABLE_SYM" (fun () -> sthm SHIFTABLE_SYM);;
attempt "CYCLES_PRIME_LEMMA" (fun () -> sthm CYCLES_PRIME_LEMMA);;
attempt "FRIENDSHIP" (fun () -> sthm FRIENDSHIP);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
