(* Load-fidelity test for 100/wilson.ml (translated by tools/translator). Keep
   in sync with 100/wilson/wilson_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "Library/prime.ml";;
#use "Library/iter.ml";;
#use "Library/pocklington.ml";;
start_trace ();;
#use "100/wilson.ml";;
show_trace "100/wilson";;
(* BEGIN generated theorem list *)
attempt "FACT_NPRODUCT" (fun () -> sthm FACT_NPRODUCT);;
attempt "FACT_NPRODUCT_ALT" (fun () -> sthm FACT_NPRODUCT_ALT);;
attempt "NPRODUCT_PAIRUP_INDUCT" (fun () -> sthm NPRODUCT_PAIRUP_INDUCT);;
attempt "NPRODUCT_PAIRUP" (fun () -> sthm NPRODUCT_PAIRUP);;
attempt "WILSON" (fun () -> sthm WILSON);;
attempt "WILSON_EQ" (fun () -> sthm WILSON_EQ);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
