(* Load-fidelity test for 100/bernoulli.ml (translated by tools/translator). Keep
   in sync with 100/bernoulli/bernoulli_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "Library/binomial.ml";;
#use "Library/analysis.ml";;
#use "Library/transc.ml";;
start_trace ();;
#use "100/bernoulli.ml";;
show_trace "100/bernoulli";;
(* BEGIN generated theorem list *)
attempt "SUM_DIFFS" (fun () -> sthm SUM_DIFFS);;
attempt "DIFF_SUM" (fun () -> sthm DIFF_SUM);;
attempt "bernoulli" (fun () -> sthm bernoulli);;
attempt "BERNOULLI" (fun () -> sthm BERNOULLI);;
attempt "bernpoly" (fun () -> sthm bernpoly);;
attempt "DIFF_BERNPOLY" (fun () -> sthm DIFF_BERNPOLY);;
attempt "INTEGRALS_EQ" (fun () -> sthm INTEGRALS_EQ);;
attempt "RECURRENCE_BERNPOLY" (fun () -> sthm RECURRENCE_BERNPOLY);;
attempt "SUM_OF_POWERS" (fun () -> sthm SUM_OF_POWERS);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
