(* Load-fidelity test for 100/liouville.ml (translated by tools/translator). Keep
   in sync with 100/liouville/liouville_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "Library/floor.ml";;
#use "Library/analysis.ml";;
#use "Library/poly.ml";;
start_trace ();;
#use "100/liouville.ml";;
show_trace "100/liouville";;
(* BEGIN generated theorem list *)
attempt "algebraic" (fun () -> sthm algebraic);;
attempt "transcendental" (fun () -> sthm transcendental);;
attempt "REAL_INTEGER_EQ_0" (fun () -> sthm REAL_INTEGER_EQ_0);;
attempt "FACT_LE_REFL" (fun () -> sthm FACT_LE_REFL);;
attempt "EXP_LE_REFL" (fun () -> sthm EXP_LE_REFL);;
attempt "MVT_INEQ" (fun () -> sthm MVT_INEQ);;
attempt "POLY_MULTIPLE_INTEGER" (fun () -> sthm POLY_MULTIPLE_INTEGER);;
attempt "SEPARATE_FINITE_SET" (fun () -> sthm SEPARATE_FINITE_SET);;
attempt "POLY_ROOT_SEPARATE_LE" (fun () -> sthm POLY_ROOT_SEPARATE_LE);;
attempt "POLY_ROOT_SEPARATE_LT" (fun () -> sthm POLY_ROOT_SEPARATE_LT);;
attempt "POLY_BOUND_INTERVAL" (fun () -> sthm POLY_BOUND_INTERVAL);;
attempt "LIOUVILLE_INTERVAL" (fun () -> sthm LIOUVILLE_INTERVAL);;
attempt "LIOUVILLE" (fun () -> sthm LIOUVILLE);;
attempt "LIOUVILLE_IRRATIONAL" (fun () -> sthm LIOUVILLE_IRRATIONAL);;
attempt "liouville" (fun () -> sthm liouville);;
attempt "LIOUVILLE_SUM_BOUND" (fun () -> sthm LIOUVILLE_SUM_BOUND);;
attempt "LIOUVILLE_PSUM_BOUND" (fun () -> sthm LIOUVILLE_PSUM_BOUND);;
attempt "LIOUVILLE_SUMS" (fun () -> sthm LIOUVILLE_SUMS);;
attempt "LIOUVILLE_PSUM_LE" (fun () -> sthm LIOUVILLE_PSUM_LE);;
attempt "LIOUVILLE_PSUM_LT" (fun () -> sthm LIOUVILLE_PSUM_LT);;
attempt "LIOVILLE_PSUM_DIFF" (fun () -> sthm LIOVILLE_PSUM_DIFF);;
attempt "TRANSCENDENTAL_LIOUVILLE" (fun () -> sthm TRANSCENDENTAL_LIOUVILLE);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
