(* Load-fidelity test for 100/leibniz.ml (translated by tools/translator). Keep
   in sync with 100/leibniz/leibniz_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "Library/analysis.ml";;
#use "Library/transc.ml";;
start_trace ();;
#use "100/leibniz.ml";;
show_trace "100/leibniz";;
(* BEGIN generated theorem list *)
attempt "ALTERNATING_SUM_BOUNDS" (fun () -> sthm ALTERNATING_SUM_BOUNDS);;
attempt "ALTERNATING_SUM_BOUND" (fun () -> sthm ALTERNATING_SUM_BOUND);;
attempt "SUMMABLE_ALTERNATING" (fun () -> sthm SUMMABLE_ALTERNATING);;
attempt "REAL_ATN_POWSER_ALT" (fun () -> sthm REAL_ATN_POWSER_ALT);;
attempt "SUMMABLE_LEIBNIZ" (fun () -> sthm SUMMABLE_LEIBNIZ);;
attempt "SUM_DIFFERENCES" (fun () -> sthm SUM_DIFFERENCES);;
attempt "SUM_REARRANGE_LEMMA" (fun () -> sthm SUM_REARRANGE_LEMMA);;
attempt "SUM_BOUNDS_LEMMA" (fun () -> sthm SUM_BOUNDS_LEMMA);;
attempt "SUM_BOUND_LEMMA" (fun () -> sthm SUM_BOUND_LEMMA);;
attempt "LEIBNIZ_PI" (fun () -> sthm LEIBNIZ_PI);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
