(* Load-fidelity test for 100/inclusion_exclusion.ml (translated by tools/translator). Keep
   in sync with 100/inclusion_exclusion/inclusion_exclusion_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
start_trace ();;
#use "100/inclusion_exclusion.ml";;
show_trace "100/inclusion_exclusion";;
(* BEGIN generated theorem list *)
attempt "SUBSET_INSERT_EXISTS" (fun () -> sthm SUBSET_INSERT_EXISTS);;
attempt "INCLUSION_EXCLUSION_REAL_RESTRICTED_INDEXED" (fun () -> sthm INCLUSION_EXCLUSION_REAL_RESTRICTED_INDEXED);;
attempt "INCLUSION_EXCLUSION_REAL_RESTRICTED" (fun () -> sthm INCLUSION_EXCLUSION_REAL_RESTRICTED);;
attempt "INCLUSION_EXCLUSION_REAL_INDEXED" (fun () -> sthm INCLUSION_EXCLUSION_REAL_INDEXED);;
attempt "INCLUSION_EXCLUSION_REAL" (fun () -> sthm INCLUSION_EXCLUSION_REAL);;
attempt "INCLUSION_EXCLUSION" (fun () -> sthm INCLUSION_EXCLUSION);;
attempt "INCLUSION_EXCLUSION_USUAL" (fun () -> sthm INCLUSION_EXCLUSION_USUAL);;
attempt "FINITE_SUBSETS_RESTRICT" (fun () -> sthm FINITE_SUBSETS_RESTRICT);;
attempt "CARD_ADJUST_LEMMA" (fun () -> sthm CARD_ADJUST_LEMMA);;
attempt "CARD_SUBSETS_STEP" (fun () -> sthm CARD_SUBSETS_STEP);;
attempt "CARD_SUBSUPERSETS_EVEN_ODD" (fun () -> sthm CARD_SUBSUPERSETS_EVEN_ODD);;
attempt "SUM_ALTERNATING_CANCELS" (fun () -> sthm SUM_ALTERNATING_CANCELS);;
attempt "INCLUSION_EXCLUSION_SYMMETRIC" (fun () -> sthm INCLUSION_EXCLUSION_SYMMETRIC);;
attempt "INCLUSION_EXCLUSION_MOBIUS" (fun () -> sthm INCLUSION_EXCLUSION_MOBIUS);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
