(* Load-fidelity test for 100/realsuncountable.ml (translated by tools/translator). Keep
   in sync with 100/realsuncountable/realsuncountable_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "Library/wo.ml";;
#use "Library/card.ml";;
#use "Library/analysis.ml";;
start_trace ();;
#use "100/realsuncountable.ml";;
show_trace "100/realsuncountable";;
(* BEGIN generated theorem list *)
attempt "countable" (fun () -> sthm countable);;
attempt "repeating" (fun () -> sthm repeating);;
attempt "BINARY_BOUND" (fun () -> sthm BINARY_BOUND);;
attempt "BINARY_DIV_POW2" (fun () -> sthm BINARY_DIV_POW2);;
attempt "PLUS_MOD_REFL" (fun () -> sthm PLUS_MOD_REFL);;
attempt "BINARY_PLUS_DIV_POW2" (fun () -> sthm BINARY_PLUS_DIV_POW2);;
attempt "BINARY_UNIQUE_LEMMA" (fun () -> sthm BINARY_UNIQUE_LEMMA);;
attempt "COUNTABLE_REPEATING" (fun () -> sthm COUNTABLE_REPEATING);;
attempt "canonical" (fun () -> sthm canonical);;
attempt "UNCOUNTABLE_CANONICAL" (fun () -> sthm UNCOUNTABLE_CANONICAL);;
attempt "SUM_BINSEQUENCE_LBOUND" (fun () -> sthm SUM_BINSEQUENCE_LBOUND);;
attempt "SUM_BINSEQUENCE_UBOUND_SHARP" (fun () -> sthm SUM_BINSEQUENCE_UBOUND_SHARP);;
attempt "SUMMABLE_BINSEQUENCE" (fun () -> sthm SUMMABLE_BINSEQUENCE);;
attempt "SUMS_BINSEQUENCE" (fun () -> sthm SUMS_BINSEQUENCE);;
attempt "SUM_BINSEQUENCE_UBOUND_LE" (fun () -> sthm SUM_BINSEQUENCE_UBOUND_LE);;
attempt "SUMINF_INJ_LEMMA" (fun () -> sthm SUMINF_INJ_LEMMA);;
attempt "UNCOUNTABLE_REALS" (fun () -> sthm UNCOUNTABLE_REALS);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
