(* Reference behaviour of basics.ml. Keep in sync with
   basics/basics_ref_test.mbt. *)
let sl f l = "[" ^ String.concat "; " (map f l) ^ "]";;
let a = mk_vartype "A" and b = mk_vartype "B";;
let fn x y = mk_fun_ty x y;;
let _ = new_type("num",0);;
let num_ty = mk_type("num",[]);;
let bb = fn bool_ty (fn bool_ty bool_ty);;
let _ = map new_constant
  ["/\\",bb; "\\/",bb; "==>",bb; "~",fn bool_ty bool_ty;
   "!",fn (fn a bool_ty) bool_ty; "?",fn (fn a bool_ty) bool_ty;
   "NUMERAL",fn num_ty num_ty; "BIT0",fn num_ty num_ty; "BIT1",fn num_ty num_ty;
   "_0",num_ty; "GEQ",fn a (fn a bool_ty); "GABS",fn (fn a bool_ty) a;
   "LET",fn (fn a b) (fn a b); "LET_END",fn a a;
   "CONS",fn a (fn (mk_type("fun",[num_ty;a])) (mk_type("fun",[num_ty;a])));
   "NIL",mk_type("fun",[num_ty;a]); "SUC",fn num_ty num_ty];;
let p = mk_var("p",bool_ty) and q = mk_var("q",bool_ty) and r = mk_var("r",bool_ty);;
let x = mk_var("x",a) and y = mk_var("y",a) and z = mk_var("z",a);;
let f = mk_var("f",fn a (fn a a)) and g = mk_var("g",fn a a);;
let n = mk_var("n",num_ty) and m = mk_var("m",num_ty);;
let conj l r = mk_binary "/\\" (l,r) and imp l r = mk_binary "==>" (l,r);;
let disj l r = mk_binary "\\/" (l,r);;
let forall v t = mk_binder "!" (v,t) and exists v t = mk_binder "?" (v,t);;
attempt "genvar" (fun () -> sl stm [genvar a; genvar bool_ty]);;
attempt "dest_fun_ty" (fun () -> let x,y = dest_fun_ty (fn a bool_ty) in sty x ^ sty y);;
attempt "dest_fun_ty_bad" (fun () -> let x,y = dest_fun_ty bool_ty in sty x ^ sty y);;
attempt "occurs_in" (fun () -> string_of_bool (occurs_in a (fn b (fn a b))) ^ string_of_bool (occurs_in bool_ty (fn a b)));;
attempt "tysubst" (fun () -> sty (tysubst [num_ty,fn a a; b,a] (fn (fn a a) (fn a bool_ty))));;
attempt "list_mk_comb" (fun () -> stm (list_mk_comb(f,[x;y])));;
attempt "list_mk_comb_bad" (fun () -> stm (list_mk_comb(g,[x;y])));;
attempt "list_mk_abs" (fun () -> stm (list_mk_abs([x;y],mk_comb(mk_comb(f,x),y))));;
attempt "strip_comb" (fun () -> let h,args = strip_comb (list_mk_comb(f,[x;y])) in stm h ^ sl stm args);;
attempt "strip_abs" (fun () -> let vs,bd = strip_abs (list_mk_abs([x;y],x)) in sl stm vs ^ stm bd);;
attempt "variants" (fun () -> sl stm (variants [x; mk_var("x'",a)] [x;x;y]));;
attempt "variables" (fun () -> sl stm (variables (mk_abs(z, mk_comb(mk_comb(f,x),mk_comb(g,y))))));;
let tbig = mk_abs(y, mk_comb(mk_comb(f, mk_comb(g,x)), y));;
attempt "subst" (fun () -> stm (subst [y, mk_comb(g,x)] tbig));;
attempt "subst_capture" (fun () -> stm (subst [mk_comb(g,y), x] tbig));;
attempt "subst_noop" (fun () -> stm (subst [x,x] tbig));;
attempt "alpha" (fun () -> stm (alpha z (mk_abs(x, mk_comb(g,x)))));;
attempt "alpha_bad" (fun () -> stm (alpha y (mk_abs(x, mk_comb(f,x) |> fun t -> mk_comb(t,y)))));;
attempt "type_match" (fun () -> sl (fun (t,v) -> sty t ^ "/" ^ sty v) (type_match (fn a (fn b a)) (fn num_ty (fn bool_ty num_ty)) []));;
attempt "type_match_bad" (fun () -> sl (fun (t,v) -> sty t ^ "/" ^ sty v) (type_match (fn a (fn b a)) (fn num_ty (fn bool_ty bool_ty)) []));;
attempt "type_match_bad2" (fun () -> sl (fun (t,v) -> sty t ^ "/" ^ sty v) (type_match (fn a a) bool_ty []));;
attempt "mk_mconst" (fun () -> stm (mk_mconst("!", fn (fn num_ty bool_ty) bool_ty)));;
attempt "mk_mconst_bad" (fun () -> stm (mk_mconst("!", fn num_ty bool_ty)));;
attempt "mk_icomb" (fun () -> stm (mk_icomb(mk_const("!",[]), mk_abs(n, mk_comb(mk_const("~",[]), p)))));;
attempt "mk_icomb_nonfun" (fun () -> stm (mk_icomb(mk_const("_0",[]), n)));;
attempt "list_mk_icomb" (fun () -> stm (list_mk_icomb "CONS" [n; mk_const("NIL",[a,a]) |> inst [num_ty,a]]));;
attempt "thm_frees" (fun () -> sl stm (thm_frees (ASSUME (mk_eq(mk_comb(g,x),y)))));;
attempt "free_in" (fun () -> String.concat "," (map string_of_bool
  [free_in (mk_comb(g,x)) tbig; free_in y tbig; free_in (mk_comb(g,y)) (mk_abs(y, mk_comb(g,y)))]));;
attempt "find_term" (fun () -> stm (find_term is_var tbig));;
attempt "find_term_bad" (fun () -> stm (find_term is_const tbig));;
attempt "find_terms" (fun () -> sl stm (find_terms (fun t -> is_var t || is_comb t) tbig));;
let big = conj (imp p q) (conj (disj q r) (mk_comb(mk_const("~",[]),p)));;
attempt "conjuncts" (fun () -> sl stm (conjuncts big));;
attempt "disjuncts" (fun () -> sl stm (disjuncts (disj (disj p q) (disj r p))));;
attempt "binops" (fun () -> sl stm (binops (mk_const("/\\",[])) big));;
attempt "dest_imp" (fun () -> let l,r = dest_imp (imp p q) in stm l ^ stm r);;
attempt "dest_imp_bad" (fun () -> let l,r = dest_imp p in stm l ^ stm r);;
attempt "dest_neg" (fun () -> stm (dest_neg (mk_comb(mk_const("~",[]),p))));;
attempt "dest_neg_bad" (fun () -> stm (dest_neg p));;
let qf = forall x (exists y (mk_eq(x,y)));;
attempt "strip_forall" (fun () -> let vs,bd = strip_forall qf in sl stm vs ^ stm bd);;
attempt "strip_exists" (fun () -> let vs,bd = strip_exists (snd(dest_forall qf)) in sl stm vs ^ stm bd);;
attempt "is_forall" (fun () -> string_of_bool (is_forall qf) ^ string_of_bool (is_exists qf));;
let num_tm k = let rec bits k = if k = 0 then mk_const("_0",[]) else mk_comb(mk_const((if k mod 2 = 0 then "BIT0" else "BIT1"),[]), bits (k / 2)) in mk_comb(mk_const("NUMERAL",[]), bits k);;
attempt "dest_numeral" (fun () -> String.concat "," (map (fun k -> string_of_num (dest_numeral (num_tm k))) [0;1;2;5;1000000]));;
attempt "dest_numeral_bad" (fun () -> string_of_num (dest_numeral (mk_comb(mk_const("NUMERAL",[]), n))));;
let nl = list_mk_icomb "CONS" [n; list_mk_icomb "CONS" [m; inst [num_ty,a] (mk_const("NIL",[]))]];;
attempt "dest_list" (fun () -> sl stm (dest_list nl));;
attempt "dest_list_bad" (fun () -> sl stm (dest_list n));;
attempt "is_list" (fun () -> string_of_bool (is_list nl) ^ string_of_bool (is_list n));;
let pr = mk_comb(mk_comb(f,x),y);;
attempt "mk_gabs_var" (fun () -> stm (mk_gabs(x, pr)));;
attempt "mk_gabs" (fun () -> stm (mk_gabs(mk_comb(g,x), pr)));;
attempt "dest_gabs" (fun () -> let v,bd = dest_gabs (mk_gabs(mk_comb(g,x), pr)) in stm v ^ " | " ^ stm bd);;
attempt "dest_gabs_bad" (fun () -> let v,bd = dest_gabs pr in stm v ^ stm bd);;
attempt "strip_gabs" (fun () -> let vs,bd = strip_gabs (list_mk_gabs([mk_comb(g,x); y], pr)) in sl stm vs ^ " | " ^ stm bd);;
let lt = mk_let([x, mk_comb(g,z); y, z], pr);;
attempt "mk_let" (fun () -> stm lt);;
attempt "dest_let" (fun () -> let eqs,bd = dest_let lt in sl (fun (l,r) -> stm l ^ "=" ^ stm r) eqs ^ " in " ^ stm bd);;
attempt "dest_let_bad" (fun () -> let eqs,bd = dest_let pr in stm bd);;
attempt "mk_finty_needs_types" (fun () -> sty (mk_finty (num 6)));;
let _ = new_type("1",0) and _ = new_type("tybit0",1) and _ = new_type("tybit1",1);;
attempt "mk_finty" (fun () -> String.concat "," (map (fun k -> sty (mk_finty (num k))) [1;2;6;13]));;
attempt "mk_finty_bad" (fun () -> sty (mk_finty (num 0)));;
attempt "dest_finty" (fun () -> String.concat "," (map (fun k -> string_of_num (dest_finty (mk_finty (num k)))) [1;2;6;13]));;
attempt "make_args" (fun () -> sl stm (make_args "x" [x; mk_var("x1",a)] [a;bool_ty;a]) ^ sl stm (make_args "x" [x] [a]));;
attempt "find_path" (fun () -> find_path ((=) y) (mk_abs(z, pr)));;
attempt "find_path_bad" (fun () -> find_path ((=) p) pr);;
attempt "follow_path" (fun () -> stm (follow_path "brr" (mk_abs(z, mk_comb(mk_comb(f,x), mk_comb(g,y))))));;
let atomic = imp (conj p (mk_eq(q,mk_comb(mk_const("~",[]),r)))) (disj (mk_eq(x,y)) (mk_comb(mk_const("~",[]),p)));;
attempt "atoms" (fun () -> sl stm (atoms atomic));;
attempt "atoms_bad" (fun () -> sl stm (atoms x));;
attempt "mk_eq_bad" (fun () -> stm (mk_eq(x,p)));;
attempt "aconv" (fun () -> string_of_bool (aconv (mk_abs(x,x)) (mk_abs(y,y))));;
attempt "genvar_after" (fun () -> stm (genvar a));;
