(* Load-fidelity and behaviour test for bool.ml. Keep in sync with
   bool/bool_ref_test.mbt. *)
#use "bool.ml";;
let th name f = attempt name (fun () -> sthm (f ()));;
let tm s = parse_term s;;
out ("constants = " ^ String.concat " " (map fst (constants())));;
out ("types = " ^ String.concat " " (map fst (types())));;
out ("definitions = " ^ String.concat " ;; " (map sthm (definitions())));;
out ("axioms = " ^ string_of_int (length (axioms())));;
out ("infixes = " ^ String.concat " " (map (fun (s,(n,a)) -> s ^ "/" ^ string_of_int n ^ a) (infixes())));;
out ("binders = " ^ String.concat " " (binders()));;
out ("prefixes = " ^ String.concat " " (prefixes()));;
out ("interface = " ^ String.concat " " (map (fun (s,(c,ty)) -> s ^ "=" ^ c ^ ":" ^ sty ty) !the_interface));;
List.iter (fun (n,t) -> th n (fun () -> t))
  ["T_DEF",T_DEF; "TRUTH",TRUTH; "AND_DEF",AND_DEF; "IMP_DEF",IMP_DEF;
   "FORALL_DEF",FORALL_DEF; "EXISTS_DEF",EXISTS_DEF; "OR_DEF",OR_DEF;
   "F_DEF",F_DEF; "NOT_DEF",NOT_DEF; "EXISTS_UNIQUE_DEF",EXISTS_UNIQUE_DEF];;
let a = tm "a:bool" and b = tm "b:bool" and c = tm "c:bool";;
let ha = ASSUME a and hb = ASSUME b;;
th "EQT_INTRO" (fun () -> EQT_INTRO ha);;
th "EQT_ELIM" (fun () -> EQT_ELIM (EQT_INTRO ha));;
th "EQT_ELIM_bad" (fun () -> EQT_ELIM ha);;
th "CONJ" (fun () -> CONJ ha hb);;
th "CONJUNCT1" (fun () -> CONJUNCT1 (CONJ ha hb));;
th "CONJUNCT2" (fun () -> CONJUNCT2 (CONJ ha hb));;
th "CONJUNCT1_bad" (fun () -> CONJUNCT1 ha);;
attempt "CONJUNCTS" (fun () -> String.concat " ;; " (map sthm (CONJUNCTS (ASSUME (tm "a /\\ (b /\\ c) /\\ d")))));;
th "MP" (fun () -> MP (ASSUME (tm "a ==> b")) ha);;
th "MP_bad" (fun () -> MP (ASSUME (tm "a ==> b")) hb);;
th "DISCH" (fun () -> DISCH a (CONJ ha hb));;
th "DISCH_ALL" (fun () -> DISCH_ALL (CONJ ha hb));;
th "UNDISCH" (fun () -> UNDISCH (ASSUME (tm "a ==> b ==> c")));;
th "UNDISCH_ALL" (fun () -> UNDISCH_ALL (ASSUME (tm "a ==> b ==> c")));;
th "IMP_ANTISYM_RULE" (fun () -> IMP_ANTISYM_RULE (ASSUME (tm "a ==> b")) (ASSUME (tm "b ==> a")));;
th "ADD_ASSUM" (fun () -> ADD_ASSUM c ha);;
attempt "EQ_IMP_RULE" (fun () -> let x,y = EQ_IMP_RULE (ASSUME (tm "a <=> b")) in sthm x ^ " ;; " ^ sthm y);;
th "IMP_TRANS" (fun () -> IMP_TRANS (ASSUME (tm "a ==> b")) (ASSUME (tm "b ==> c")));;
th "IMP_TRANS_bad" (fun () -> IMP_TRANS (ASSUME (tm "a ==> b")) (ASSUME (tm "c ==> c")));;
let fa = ASSUME (tm "!x:A. (P:A->bool) x");;
th "SPEC" (fun () -> SPEC (tm "y:A") fa);;
th "SPEC_bad" (fun () -> SPEC (tm "y:B") fa);;
th "SPECL" (fun () -> SPECL [tm "u:num"; tm "v:num"] (ASSUME (tm "!x y:num. (R:num->num->bool) x y")));;
th "SPEC_ALL" (fun () -> SPEC_ALL (ASSUME (tm "!x y:num. (R:num->num->bool) x y /\\ R y x")));;
th "ISPEC" (fun () -> ISPEC (tm "n:num") (ASSUME (tm "!x:A. x = x")));;
th "ISPECL" (fun () -> ISPECL [tm "n:num"; tm "T"] (ASSUME (tm "!(x:A) (y:B). x = x /\\ y = y")));;
th "GEN" (fun () -> GEN (tm "x:A") (ASSUME (tm "(P:A->bool) x ==> P x") |> DISCH_ALL));;
th "GEN_bad" (fun () -> GEN (tm "x:A") (ASSUME (tm "(P:A->bool) x")));;
th "GENL" (fun () -> GENL [tm "x:A"; tm "y:A"] (REFL (tm "(f:A->A->A) x y")));;
th "GEN_ALL" (fun () -> GEN_ALL (DISCH_ALL (ASSUME (tm "(P:A->B->bool) x y"))));;
th "EXISTS" (fun () -> EXISTS (tm "?x:num. x = x", tm "n:num") (REFL (tm "n:num")));;
th "SIMPLE_EXISTS" (fun () -> SIMPLE_EXISTS (tm "n:num") (REFL (tm "n:num")));;
th "CHOOSE" (fun () -> CHOOSE (tm "x:A", ASSUME (tm "?x:A. (P:A->bool) x")) (ADD_ASSUM (tm "(P:A->bool) x") (REFL (tm "T"))));;
th "SIMPLE_CHOOSE" (fun () -> SIMPLE_CHOOSE (tm "x:A") (ADD_ASSUM (tm "(P:A->bool) x") (REFL (tm "T"))));;
th "DISJ1" (fun () -> DISJ1 ha b);;
th "DISJ2" (fun () -> DISJ2 a hb);;
th "DISJ_CASES" (fun () -> DISJ_CASES (ASSUME (tm "a \\/ b")) (DISJ2 b ha) (DISJ1 hb a));;
th "DISJ_CASES_bad" (fun () -> DISJ_CASES (ASSUME (tm "a \\/ b")) ha hb);;
th "SIMPLE_DISJ_CASES" (fun () -> SIMPLE_DISJ_CASES (ADD_ASSUM a (REFL (tm "T"))) (ADD_ASSUM b (REFL (tm "T"))));;
th "NOT_ELIM" (fun () -> NOT_ELIM (ASSUME (tm "~a")));;
th "NOT_INTRO" (fun () -> NOT_INTRO (ASSUME (tm "a ==> F")));;
th "EQF_INTRO" (fun () -> EQF_INTRO (ASSUME (tm "~a")));;
th "EQF_ELIM" (fun () -> EQF_ELIM (ASSUME (tm "a <=> F")));;
th "CONTR" (fun () -> CONTR a (ASSUME (tm "F")));;
th "CONTR_bad" (fun () -> CONTR a ha);;
th "EXISTENCE" (fun () -> EXISTENCE (ASSUME (tm "?!x:num. x = n")));;
th "PINST" (fun () -> PINST [bool_ty, aty] [tm "T", mk_var("x",aty)] (REFL (tm "(f:A->A) x")));;
th "PROVE_HYP" (fun () -> PROVE_HYP ha (CONJ ha hb));;
attempt "mk_iff" (fun () -> stm (mk_iff (a, b)));;
attempt "dest_iff_bad" (fun () -> let l,r = dest_iff (tm "(x:num) = y") in stm l);;
attempt "mk_neg" (fun () -> stm (mk_neg a));;
attempt "mk_neg_bad" (fun () -> stm (mk_neg (tm "x:num")));;
attempt "verbose" (fun () -> stm (tm "forall x. exists y. x = y /\\ true"));;
attempt "print" (fun () -> string_of_term (tm "!x. ?y. x = y /\\ (p <=> q) ==> ~r \\/ F"));;
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_pgenvar" (fun () -> stm (tm "{x | T}"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
