(* Load-fidelity test for Boyer_Moore/terms_and_clauses.ml (translated by tools/translator). Keep
   in sync with boyer_moore/terms_and_clauses/terms_and_clauses_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "Boyer_Moore/support.ml";;
#use "Boyer_Moore/struct_equal.ml";;
#use "Boyer_Moore/shells.ml";;
#use "Boyer_Moore/environment.ml";;
#use "Boyer_Moore/clausal_form.ml";;
#use "Boyer_Moore/waterfall.ml";;
#use "Boyer_Moore/rewrite_rules.ml";;
#use "Boyer_Moore/definitions.ml";;
start_trace ();;
#use "Boyer_Moore/terms_and_clauses.ml";;
show_trace "Boyer_Moore/terms_and_clauses";;
(* BEGIN generated theorem list *)
attempt "COND_T" (fun () -> sthm COND_T);;
attempt "COND_F" (fun () -> sthm COND_F);;
attempt "COND_LEFT" (fun () -> sthm COND_LEFT);;
attempt "COND_RIGHT" (fun () -> sthm COND_RIGHT);;
attempt "COND_RIGHT_F" (fun () -> sthm COND_RIGHT_F);;
attempt "COND_T_F" (fun () -> sthm COND_T_F);;
attempt "EQ_T" (fun () -> sthm EQ_T);;
attempt "EQ_EQ" (fun () -> sthm EQ_EQ);;
attempt "EQ_F" (fun () -> sthm EQ_F);;
attempt "COND_OR" (fun () -> sthm COND_OR);;
attempt "NOT_EQ_F" (fun () -> sthm NOT_EQ_F);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
