(* Load-fidelity test for Boyer_Moore/clausal_form.ml (translated by tools/translator). Keep
   in sync with boyer_moore/clausal_form/clausal_form_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "Boyer_Moore/support.ml";;
#use "Boyer_Moore/struct_equal.ml";;
#use "Boyer_Moore/shells.ml";;
#use "Boyer_Moore/environment.ml";;
start_trace ();;
#use "Boyer_Moore/clausal_form.ml";;
show_trace "Boyer_Moore/clausal_form";;
(* BEGIN generated theorem list *)
attempt "IMP_DISJ_THM" (fun () -> sthm IMP_DISJ_THM);;
attempt "RIGHT_OR_OVER_AND" (fun () -> sthm RIGHT_OR_OVER_AND);;
attempt "LEFT_OR_OVER_AND" (fun () -> sthm LEFT_OR_OVER_AND);;
attempt "EQ_EXPAND" (fun () -> sthm EQ_EXPAND);;
attempt "IMP_EXPAND" (fun () -> sthm IMP_EXPAND);;
attempt "COND_EXPAND" (fun () -> sthm COND_EXPAND);;
attempt "NOT_NOT_NORM" (fun () -> sthm NOT_NOT_NORM);;
attempt "NOT_CONJ_NORM" (fun () -> sthm NOT_CONJ_NORM);;
attempt "NOT_DISJ_NORM" (fun () -> sthm NOT_DISJ_NORM);;
attempt "LEFT_DIST_NORM" (fun () -> sthm LEFT_DIST_NORM);;
attempt "RIGHT_DIST_NORM" (fun () -> sthm RIGHT_DIST_NORM);;
attempt "CONJ_ASSOC_NORM" (fun () -> sthm CONJ_ASSOC_NORM);;
attempt "DISJ_ASSOC_NORM" (fun () -> sthm DISJ_ASSOC_NORM);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
