(* Load-fidelity test for Boyer_Moore/rewrite_rules.ml (translated by tools/translator). Keep
   in sync with boyer_moore/rewrite_rules/rewrite_rules_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "Boyer_Moore/support.ml";;
#use "Boyer_Moore/struct_equal.ml";;
#use "Boyer_Moore/shells.ml";;
#use "Boyer_Moore/environment.ml";;
#use "Boyer_Moore/clausal_form.ml";;
#use "Boyer_Moore/waterfall.ml";;
start_trace ();;
#use "Boyer_Moore/rewrite_rules.ml";;
show_trace "Boyer_Moore/rewrite_rules";;
(* BEGIN generated theorem list *)
attempt "NOT_IMP_EQ_EQ_EQ_OR" (fun () -> sthm NOT_IMP_EQ_EQ_EQ_OR);;
attempt "IMP_EQ_EQ_EQ_OR_NOT" (fun () -> sthm IMP_EQ_EQ_EQ_OR_NOT);;
attempt "NOT_IMP_EQ_OR_EQ_EQ_OR_OR" (fun () -> sthm NOT_IMP_EQ_OR_EQ_EQ_OR_OR);;
attempt "IMP_EQ_OR_EQ_EQ_OR_NOT_OR" (fun () -> sthm IMP_EQ_OR_EQ_EQ_OR_NOT_OR);;
attempt "IMP_EQ_EQ_EQ_NOT_OR" (fun () -> sthm IMP_EQ_EQ_EQ_NOT_OR);;
attempt "IMP_NOT_EQ_EQ_EQ_OR" (fun () -> sthm IMP_NOT_EQ_EQ_EQ_OR);;
attempt "T_OR" (fun () -> sthm T_OR);;
attempt "OR_T" (fun () -> sthm OR_T);;
attempt "F_OR" (fun () -> sthm F_OR);;
attempt "OR_F" (fun () -> sthm OR_F);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
