(* Load-fidelity test for calc_int.ml (translated by tools/translator). Keep
   in sync with calc_int/calc_int_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
start_trace ();;
#use "calc_int.ml";;
show_trace "calc_int";;
(* BEGIN generated theorem list *)
attempt "REAL_ADD_AC" (fun () -> sthm REAL_ADD_AC);;
attempt "REAL_ADD_RINV" (fun () -> sthm REAL_ADD_RINV);;
attempt "REAL_EQ_ADD_LCANCEL" (fun () -> sthm REAL_EQ_ADD_LCANCEL);;
attempt "REAL_EQ_ADD_RCANCEL" (fun () -> sthm REAL_EQ_ADD_RCANCEL);;
attempt "REAL_MUL_RZERO" (fun () -> sthm REAL_MUL_RZERO);;
attempt "REAL_MUL_LZERO" (fun () -> sthm REAL_MUL_LZERO);;
attempt "REAL_NEG_NEG" (fun () -> sthm REAL_NEG_NEG);;
attempt "REAL_MUL_RNEG" (fun () -> sthm REAL_MUL_RNEG);;
attempt "REAL_MUL_LNEG" (fun () -> sthm REAL_MUL_LNEG);;
attempt "REAL_NEG_ADD" (fun () -> sthm REAL_NEG_ADD);;
attempt "REAL_ADD_RID" (fun () -> sthm REAL_ADD_RID);;
attempt "REAL_NEG_0" (fun () -> sthm REAL_NEG_0);;
attempt "REAL_LE_LNEG" (fun () -> sthm REAL_LE_LNEG);;
attempt "REAL_LE_NEG2" (fun () -> sthm REAL_LE_NEG2);;
attempt "REAL_LE_RNEG" (fun () -> sthm REAL_LE_RNEG);;
attempt "REAL_OF_NUM_POW" (fun () -> sthm REAL_OF_NUM_POW);;
attempt "REAL_POW_NEG" (fun () -> sthm REAL_POW_NEG);;
attempt "REAL_ABS_NUM" (fun () -> sthm REAL_ABS_NUM);;
attempt "REAL_ABS_NEG" (fun () -> sthm REAL_ABS_NEG);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (length (definitions())));;
(* BEGIN EXTRA *)
attempt "reduce_add" (fun () -> sthm (REAL_INT_REDUCE_CONV (tm "&2 + &3 * -- &4")));;
attempt "reduce_pow" (fun () -> sthm (REAL_INT_REDUCE_CONV (tm "(-- &3) pow 5")));;
attempt "reduce_abs" (fun () -> sthm (REAL_INT_REDUCE_CONV (tm "abs(-- &17) - &20")));;
attempt "reduce_cmp" (fun () -> sthm (REAL_INT_REDUCE_CONV (tm "-- &5 < &3")));;
attempt "reduce_max" (fun () -> sthm (REAL_INT_REDUCE_CONV (tm "max (&2) (-- &7)")));;
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
