(* Load-fidelity test for calc_rat.ml (translated by tools/translator). Keep
   in sync with calc_rat/calc_rat_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
start_trace ();;
#use "calc_rat.ml";;
show_trace "calc_rat";;
(* BEGIN generated theorem list *)
attempt "DECIMAL" (fun () -> sthm DECIMAL);;
attempt "RAT_LEMMA1" (fun () -> sthm RAT_LEMMA1);;
attempt "RAT_LEMMA2" (fun () -> sthm RAT_LEMMA2);;
attempt "RAT_LEMMA3" (fun () -> sthm RAT_LEMMA3);;
attempt "RAT_LEMMA4" (fun () -> sthm RAT_LEMMA4);;
attempt "RAT_LEMMA5" (fun () -> sthm RAT_LEMMA5);;
attempt "REAL_LE_TRANS_LE" (fun () -> sthm REAL_LE_TRANS_LE);;
attempt "REAL_LE_TRANS_LTE" (fun () -> sthm REAL_LE_TRANS_LTE);;
attempt "REAL_LE_TRANS_LT" (fun () -> sthm REAL_LE_TRANS_LT);;
attempt "REAL_SHRINK_RANGE" (fun () -> sthm REAL_SHRINK_RANGE);;
attempt "REAL_SHRINK_LT" (fun () -> sthm REAL_SHRINK_LT);;
attempt "REAL_SHRINK_LE" (fun () -> sthm REAL_SHRINK_LE);;
attempt "REAL_SHRINK_EQ" (fun () -> sthm REAL_SHRINK_EQ);;
attempt "REAL_SHRINK_GALOIS" (fun () -> sthm REAL_SHRINK_GALOIS);;
attempt "REAL_GROW_SHRINK" (fun () -> sthm REAL_GROW_SHRINK);;
attempt "REAL_SHRINK_GROW_EQ" (fun () -> sthm REAL_SHRINK_GROW_EQ);;
attempt "REAL_SHRINK_GROW" (fun () -> sthm REAL_SHRINK_GROW);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (length (definitions())));;
(* BEGIN EXTRA *)
attempt "rat_reduce" (fun () -> sthm (REAL_RAT_REDUCE_CONV (tm "&1 / &3 + &1 / &6")));;
attempt "rat_cmp" (fun () -> sthm (REAL_RAT_REDUCE_CONV (tm "&2 / &3 < &3 / &4")));;
attempt "rat_pow" (fun () -> sthm (REAL_RAT_REDUCE_CONV (tm "(&2 / &3) pow 3")));;
attempt "field" (fun () -> sthm (REAL_FIELD (tm "~(x = &0) ==> x * inv(x) = &1")));;
attempt "field2" (fun () -> sthm (REAL_FIELD (tm "~(a = &0) /\\ ~(b = &0) ==> inv(a * b) = inv a * inv b")));;
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
