(* Load-fidelity test for calc_num.ml (translated by tools/translator). Keep
   in sync with calc_num/calc_num_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
start_trace ();;
#use "calc_num.ml";;
show_trace "calc_num";;
(* BEGIN generated theorem list *)
attempt "ARITH_ZERO" (fun () -> sthm ARITH_ZERO);;
attempt "BIT0_0" (fun () -> sthm BIT0_0);;
attempt "BIT1_0" (fun () -> sthm BIT1_0);;
attempt "ARITH_SUC" (fun () -> sthm ARITH_SUC);;
attempt "ARITH_PRE" (fun () -> sthm ARITH_PRE);;
attempt "ARITH_ADD" (fun () -> sthm ARITH_ADD);;
attempt "ARITH_MULT" (fun () -> sthm ARITH_MULT);;
attempt "ARITH_EXP" (fun () -> sthm ARITH_EXP);;
attempt "ARITH_EVEN" (fun () -> sthm ARITH_EVEN);;
attempt "ARITH_ODD" (fun () -> sthm ARITH_ODD);;
attempt "ARITH_LE" (fun () -> sthm ARITH_LE);;
attempt "ARITH_LT" (fun () -> sthm ARITH_LT);;
attempt "ARITH_GE" (fun () -> sthm ARITH_GE);;
attempt "ARITH_GT" (fun () -> sthm ARITH_GT);;
attempt "ARITH_EQ" (fun () -> sthm ARITH_EQ);;
attempt "ARITH_SUB" (fun () -> sthm ARITH_SUB);;
attempt "ARITH" (fun () -> sthm ARITH);;
attempt "EXP_2_NE_0" (fun () -> sthm EXP_2_NE_0);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (length (definitions())));;
(* BEGIN EXTRA *)
attempt "reduce_add" (fun () -> sthm (NUM_REDUCE_CONV (tm "2 + 3 * 4 EXP 2")));;
attempt "reduce_div" (fun () -> sthm (NUM_REDUCE_CONV (tm "17 DIV 5")));;
attempt "reduce_mod" (fun () -> sthm (NUM_REDUCE_CONV (tm "100 MOD 7")));;
attempt "reduce_big" (fun () -> sthm (NUM_REDUCE_CONV (tm "2 EXP 100")));;
attempt "reduce_sub" (fun () -> sthm (NUM_REDUCE_CONV (tm "10 - 13")));;
attempt "reduce_le" (fun () -> sthm (NUM_REDUCE_CONV (tm "123456789 <= 987654321")));;
attempt "reduce_fact" (fun () -> sthm (NUM_REDUCE_CONV (tm "FACT 10")));;
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
