(* Load-fidelity and behaviour test for canon.ml (translated by
   tools/translator). Keep in sync with canon/canon_ref_test.mbt (the
   theorem list part is generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
start_trace ();;
#use "canon.ml";;
show_trace "canon";;
(* BEGIN generated theorem list *)
(* END generated theorem list *)
let tm s = parse_term s;;
let cv name c s = attempt name (fun () -> let t = tm s in sthm (c t));;
let fol = "(!x:A. P x ==> (?y. Q x y)) /\\ ~(?z. R z /\\ (P z <=> Q z z))";;
cv "PRESIMP_CONV" PRESIMP_CONV "~(a /\\ ~b) ==> (T /\\ c) \\/ F";;
cv "NNF_CONV" NNF_CONV fol;;
cv "NNFC_CONV" NNFC_CONV "~(p <=> q) \\/ (r <=> ~s)";;
cv "NNF_CONV_eq" NNF_CONV "~(p <=> q) \\/ (r <=> ~s)";;
cv "SKOLEM_CONV" SKOLEM_CONV "!x:A. ?y:B. P x y /\\ (?z:C. Q x z)";;
cv "PRENEX_CONV" PRENEX_CONV "(!x:A. P x) /\\ (?y:A. Q y) ==> R";;
cv "WEAK_DNF_CONV" WEAK_DNF_CONV "(a \\/ b) /\\ (c \\/ d)";;
cv "DNF_CONV" DNF_CONV "(a \\/ b) /\\ (c \\/ a)";;
cv "WEAK_CNF_CONV" WEAK_CNF_CONV "(a /\\ b) \\/ (c /\\ d)";;
cv "CNF_CONV" CNF_CONV "(a /\\ b) \\/ (c /\\ a)";;
cv "CONJ_CANON_CONV" CONJ_CANON_CONV "(b /\\ a) /\\ (a /\\ c)";;
cv "DISJ_CANON_CONV" DISJ_CANON_CONV "(b \\/ a) \\/ (a \\/ c)";;
cv "CONJ_ACI_RULE" CONJ_ACI_RULE "(a /\\ b) /\\ c <=> c /\\ b /\\ a";;
cv "DISJ_ACI_RULE" DISJ_ACI_RULE "(a \\/ b) \\/ c <=> c \\/ b \\/ a";;
cv "LAMBDA_ELIM_CONV" LAMBDA_ELIM_CONV "(P:(A->B)->bool) (\\x. f x y)";;
cv "CONDS_ELIM_CONV" CONDS_ELIM_CONV "(P:A->bool) (if b then x else y) /\\ c";;
cv "CONDS_CELIM_CONV" CONDS_CELIM_CONV "(P:A->bool) (if b then x else y) /\\ c";;
attempt "ASSOC_CONV" (fun () -> let t = tm "(a /\\ b) /\\ (c /\\ d)" in sthm (ASSOC_CONV CONJ_ASSOC t));;
attempt "PROP_ATOM_CONV" (fun () -> let t = tm "(a:bool) /\\ ~(b ==> (\\x:bool. x) c)" in sthm (PROP_ATOM_CONV (DEPTH_CONV BETA_CONV) t));;
attempt "GEN_NNF_CONV" (fun () -> let t = tm "~(p /\\ (q \\/ ~r))" in
  sthm (GEN_NNF_CONV true (ALL_CONV, fun t -> REFL t, REFL t) t));;
attempt "SELECT_ELIM_TAC" (fun () -> let w = tm "(P:A->bool) (@x. P x) ==> Q" in
  let (_,gls,_) = SELECT_ELIM_TAC ([], w) in slist (fun (_,t) -> stm t) gls);;
attempt "ASM_FOL_TAC" (fun () -> let w = tm "(!x:A. P x) ==> P a" in
  let (_,gls,_) = (DISCH_TAC THEN ASM_FOL_TAC) ([], w) in slist (fun (asl,t) -> slist (fun (_,th) -> stm (concl th)) asl ^ " ?- " ^ stm t) gls);;
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
