(* Load-fidelity and behaviour test for class.ml (translated by
   tools/translator). Keep in sync with class/class_ref_test.mbt (the
   theorem list part is generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
start_trace ();;
#use "class.ml";;
show_trace "class";;
(* BEGIN generated theorem list *)
attempt "ETA_AX" (fun () -> sthm ETA_AX);;
attempt "EQ_EXT" (fun () -> sthm EQ_EXT);;
attempt "FUN_EQ_THM" (fun () -> sthm FUN_EQ_THM);;
attempt "SELECT_AX" (fun () -> sthm SELECT_AX);;
attempt "EXISTS_THM" (fun () -> sthm EXISTS_THM);;
attempt "SELECT_REFL" (fun () -> sthm SELECT_REFL);;
attempt "SELECT_UNIQUE" (fun () -> sthm SELECT_UNIQUE);;
attempt "EXCLUDED_MIDDLE" (fun () -> sthm EXCLUDED_MIDDLE);;
attempt "BOOL_CASES_AX" (fun () -> sthm BOOL_CASES_AX);;
attempt "DE_MORGAN_THM" (fun () -> sthm DE_MORGAN_THM);;
attempt "NOT_CLAUSES" (fun () -> sthm NOT_CLAUSES);;
attempt "NOT_IMP" (fun () -> sthm NOT_IMP);;
attempt "CONTRAPOS_THM" (fun () -> sthm CONTRAPOS_THM);;
attempt "NOT_EXISTS_THM" (fun () -> sthm NOT_EXISTS_THM);;
attempt "EXISTS_NOT_THM" (fun () -> sthm EXISTS_NOT_THM);;
attempt "NOT_FORALL_THM" (fun () -> sthm NOT_FORALL_THM);;
attempt "FORALL_NOT_THM" (fun () -> sthm FORALL_NOT_THM);;
attempt "FORALL_BOOL_THM" (fun () -> sthm FORALL_BOOL_THM);;
attempt "EXISTS_BOOL_THM" (fun () -> sthm EXISTS_BOOL_THM);;
attempt "LEFT_FORALL_OR_THM" (fun () -> sthm LEFT_FORALL_OR_THM);;
attempt "RIGHT_FORALL_OR_THM" (fun () -> sthm RIGHT_FORALL_OR_THM);;
attempt "LEFT_OR_FORALL_THM" (fun () -> sthm LEFT_OR_FORALL_THM);;
attempt "RIGHT_OR_FORALL_THM" (fun () -> sthm RIGHT_OR_FORALL_THM);;
attempt "LEFT_IMP_FORALL_THM" (fun () -> sthm LEFT_IMP_FORALL_THM);;
attempt "LEFT_EXISTS_IMP_THM" (fun () -> sthm LEFT_EXISTS_IMP_THM);;
attempt "RIGHT_IMP_EXISTS_THM" (fun () -> sthm RIGHT_IMP_EXISTS_THM);;
attempt "RIGHT_EXISTS_IMP_THM" (fun () -> sthm RIGHT_EXISTS_IMP_THM);;
attempt "COND_DEF" (fun () -> sthm COND_DEF);;
attempt "COND_CLAUSES" (fun () -> sthm COND_CLAUSES);;
attempt "COND_EXPAND" (fun () -> sthm COND_EXPAND);;
attempt "COND_ID" (fun () -> sthm COND_ID);;
attempt "COND_RAND" (fun () -> sthm COND_RAND);;
attempt "COND_RATOR" (fun () -> sthm COND_RATOR);;
attempt "COND_ABS" (fun () -> sthm COND_ABS);;
attempt "COND_SWAP" (fun () -> sthm COND_SWAP);;
attempt "MONO_COND" (fun () -> sthm MONO_COND);;
attempt "COND_ELIM_THM" (fun () -> sthm COND_ELIM_THM);;
attempt "SKOLEM_THM" (fun () -> sthm SKOLEM_THM);;
attempt "SKOLEM_THM_GEN" (fun () -> sthm SKOLEM_THM_GEN);;
attempt "UNIQUE_SKOLEM_ALT" (fun () -> sthm UNIQUE_SKOLEM_ALT);;
attempt "UNIQUE_SKOLEM_THM" (fun () -> sthm UNIQUE_SKOLEM_THM);;
attempt "bool_INDUCT" (fun () -> sthm bool_INDUCT);;
attempt "bool_RECURSION" (fun () -> sthm bool_RECURSION);;
(* END generated theorem list *)
let tm s = parse_term s;;
let sgoal gl =
  let b = Buffer.create 80 in
  let f = Format.formatter_of_buffer b in
  pp_print_goal f gl; Format.pp_print_flush f (); String.escaped (Buffer.contents b);;
let st name f = attempt name (fun () -> let w,tac = f () in let (_,gls,_) = tac ([],w) in slist sgoal gls);;
let th name f = attempt name (fun () -> sthm (f ()));;
th "ETA_CONV" (fun () -> let t = tm "\\x:A. (f:A->B) x" in ETA_CONV t);;
th "ETA_CONV_bad" (fun () -> let t = tm "\\x:A. (f:A->A->B) x x" in ETA_CONV t);;
attempt "select" (fun () -> let t = tm "@x:A. P x" in
  let v, b = dest_select t in string_of_bool (is_select t) ^ " " ^ stm v ^ " " ^ stm b ^ " " ^ stm (mk_select(v, b)));;
th "SELECT_RULE" (fun () -> let t = tm "?x:A. P x" in SELECT_RULE (ASSUME t));;
th "SELECT_CONV" (fun () -> let t = tm "(P:A->bool) (@x. P x)" in SELECT_CONV t);;
th "TAUT1" (fun () -> let t = tm "p \\/ ~p" in TAUT t);;
th "TAUT2" (fun () -> let t = tm "(p ==> q) \\/ (q ==> p)" in TAUT t);;
th "TAUT3" (fun () -> let t = tm "(a <=> b) <=> (a /\\ b) \\/ (~a /\\ ~b)" in TAUT t);;
th "TAUT_bad" (fun () -> let t = tm "p ==> q" in TAUT t);;
th "TAUT_cond" (fun () -> let t = tm "(if b then x else y) = (if ~b then y else x:A)" in TAUT t);;
th "CCONTR" (fun () -> let p = tm "p:bool" in let th0 = ASSUME (tm "~p ==> F") in CCONTR p (UNDISCH th0));;
th "CONTRAPOS_CONV" (fun () -> let t = tm "p ==> q" in CONTRAPOS_CONV t);;
attempt "cond" (fun () -> let b = tm "b:bool" in let x = tm "x:A" in let y = tm "y:A" in
  let c = mk_cond(b, x, y) in let b', (x', y') = dest_cond c in
  string_of_bool (is_cond c) ^ " " ^ stm c ^ " " ^ stm b' ^ " " ^ stm x' ^ " " ^ stm y');;
th "COND_ELIM_CONV" (fun () -> let t = tm "(P:A->bool) (if b then x else y)" in COND_ELIM_CONV t);;
st "COND_CASES_TAC" (fun () -> let w = tm "(P:A->bool) (if b then x else y)" in w, COND_CASES_TAC);;
st "BOOL_CASES_TAC" (fun () -> let w = tm "(P:bool->bool) b" in let b = tm "b:bool" in w, BOOL_CASES_TAC b);;
st "ASM_CASES_TAC" (fun () -> let w = tm "q:bool" in let p = tm "p:bool" in w, ASM_CASES_TAC p);;
st "REFUTE_THEN" (fun () -> let w = tm "p:bool" in w, REFUTE_THEN ASSUME_TAC);;
th "new_type_definition" (fun () -> let t = tm "?b:bool. b" in
  let th0 = prove(t, EXISTS_TAC (tm "T") THEN ACCEPT_TAC TRUTH) in
  new_type_definition "unit'" ("mk_unit'","dest_unit'") th0);;
th "new_type_definition_again" (fun () -> let t = tm "?b:bool. b" in
  let th0 = prove(t, EXISTS_TAC (tm "T") THEN ACCEPT_TAC TRUTH) in
  new_type_definition "unit'" ("mk_unit'","dest_unit'") th0);;
attempt "type_definitions" (fun () -> string_of_int (length (!the_type_definitions)));;
attempt "inductive_type_store" (fun () -> String.concat " " (map fst (!inductive_type_store)));;
attempt "types" (fun () -> String.concat " " (map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (length (definitions())));;
attempt "axioms" (fun () -> String.concat " ;; " (map sthm (axioms())));;
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
