(* Load-fidelity and behaviour test for compute.ml (translated by
   tools/translator). Keep in sync with compute/compute_ref_test.mbt (the theorem
   list part is generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
start_trace ();;
#use "compute.ml";;
show_trace "compute";;
let tm s = parse_term s;;
attempt "eval_bool" (fun () -> sthm (Compute.EVAL_CONV (tm "(T /\\ F) \\/ ~F")));;
attempt "eval_cond" (fun () -> sthm (Compute.EVAL_CONV (tm "if T /\\ T then (a:A) else b")));;
attempt "eval_let" (fun () -> sthm (Compute.EVAL_CONV (tm "let x = T in x /\\ ~x")));;
attempt "eval_beta" (fun () -> sthm (Compute.EVAL_CONV (tm "(\\x:bool. x \\/ F) T")));;
attempt "eval_pair" (fun () -> sthm (Compute.EVAL_CONV (tm "FST (T, F) /\\ SND (F, T)")));;
attempt "eval_weak" (fun () -> sthm (Compute.WEAK_CBV_CONV (Compute.bool_compset ()) (tm "(\\x. x /\\ T) F")));;
attempt "eval_fail" (fun () -> sthm (Compute.EVAL_CONV (tm "p:bool")));;
let d = new_definition (tm "myneg b = if b then F else T");;
attempt "add_funs" (fun () -> Compute.add_funs [d]; sthm (Compute.EVAL_CONV (tm "myneg (myneg T)")));;
attempt "restr" (fun () -> sthm (Compute.RESTR_EVAL_CONV [tm "myneg"] (tm "myneg (T /\\ F)")));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
