(* Load-fidelity test for Divstep/divstep.ml (translated by tools/translator). Keep
   in sync with divstep/divstep/divstep_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "Library/iter.ml";;
#use "Library/integer.ml";;
#use "Library/floor.ml";;
start_trace ();;
#use "Divstep/divstep.ml";;
show_trace "Divstep/divstep";;
(* BEGIN generated theorem list *)
attempt "divstep" (fun () -> sthm divstep);;
attempt "divstep1" (fun () -> sthm divstep1);;
attempt "divstep2" (fun () -> sthm divstep2);;
attempt "DIVSTEP1_DIVSTEP2" (fun () -> sthm DIVSTEP1_DIVSTEP2);;
attempt "DIVSTEP_STAYS_ODD" (fun () -> sthm DIVSTEP_STAYS_ODD);;
attempt "DIVSTEP_STAYS_ZERO" (fun () -> sthm DIVSTEP_STAYS_ZERO);;
attempt "DIVSTEP_MAINTAINS_GCD" (fun () -> sthm DIVSTEP_MAINTAINS_GCD);;
attempt "DIVSTEP_RANGE_2SCOMPLEMENT" (fun () -> sthm DIVSTEP_RANGE_2SCOMPLEMENT);;
attempt "DIVSTEP_RANGE_SIGNMAGNITUDE" (fun () -> sthm DIVSTEP_RANGE_SIGNMAGNITUDE);;
attempt "ITER_DIVSTEP_ODD" (fun () -> sthm ITER_DIVSTEP_ODD);;
attempt "ITER_DIVSTEP_ZERO" (fun () -> sthm ITER_DIVSTEP_ZERO);;
attempt "ITER_DIVSTEP_GCD" (fun () -> sthm ITER_DIVSTEP_GCD);;
attempt "ITER_DIVSTEP_BOUND_ALT" (fun () -> sthm ITER_DIVSTEP_BOUND_ALT);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
