(* Load-fidelity test for Divstep/divstep_bounds.ml (translated by tools/translator). Keep
   in sync with divstep/divstep_bounds/divstep_bounds_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "Library/iter.ml";;
#use "Library/integer.ml";;
#use "Library/floor.ml";;
#use "Divstep/divstep.ml";;
#use "Divstep/idivstep.ml";;
#use "Divstep/hull_light.ml";;
start_trace ();;
#use "Divstep/divstep_bounds.ml";;
show_trace "Divstep/divstep_bounds";;
(* BEGIN generated theorem list *)
attempt "INTEGER_DIVSTEP_DELTA" (fun () -> sthm INTEGER_DIVSTEP_DELTA);;
attempt "ITER_DIVSTEP_ODD_ALT" (fun () -> sthm ITER_DIVSTEP_ODD_ALT);;
attempt "DIVSTEP_ENDTOEND_BITS_SIMPLE" (fun () -> sthm DIVSTEP_ENDTOEND_BITS_SIMPLE);;
attempt "IDIVSTEP_ENDTOEND_BITS_SIMPLE" (fun () -> sthm IDIVSTEP_ENDTOEND_BITS_SIMPLE);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
