(* Load-fidelity test for EC/formulary_xzprojective.ml (translated by tools/translator). Keep
   in sync with ec/formulary_xzprojective/formulary_xzprojective_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "Library/iter.ml";;
#use "Library/prime.ml";;
#use "Library/pocklington.ml";;
#use "Library/integer.ml";;
#use "Library/isum.ml";;
#use "Library/binomial.ml";;
#use "Library/products.ml";;
#use "Library/multiplicative.ml";;
#use "Library/primitive.ml";;
#use "Library/frag.ml";;
#use "Library/wo.ml";;
#use "Library/card.ml";;
#use "Library/grouptheory.ml";;
#use "Library/ringtheory.ml";;
#use "EC/misc.ml";;
#use "EC/montgomery.ml";;
#use "EC/xzprojective.ml";;
start_trace ();;
#use "EC/formulary_xzprojective.ml";;
show_trace "EC/formulary_xzprojective";;
(* BEGIN generated theorem list *)
attempt "mladd_1987_m" (fun () -> sthm mladd_1987_m);;
attempt "MLADD_1987_M" (fun () -> sthm MLADD_1987_M);;
attempt "okeya_sakurai_1" (fun () -> sthm okeya_sakurai_1);;
attempt "OKEYA_SAKURAI_1" (fun () -> sthm OKEYA_SAKURAI_1);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
