(* Load-fidelity test for EC/misc.ml (translated by tools/translator). Keep
   in sync with ec/misc/misc_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "Library/iter.ml";;
#use "Library/prime.ml";;
#use "Library/pocklington.ml";;
#use "Library/integer.ml";;
#use "Library/isum.ml";;
#use "Library/binomial.ml";;
#use "Library/products.ml";;
#use "Library/multiplicative.ml";;
#use "Library/primitive.ml";;
#use "Library/frag.ml";;
#use "Library/wo.ml";;
#use "Library/card.ml";;
#use "Library/grouptheory.ml";;
#use "Library/ringtheory.ml";;
start_trace ();;
#use "EC/misc.ml";;
show_trace "EC/misc";;
(* BEGIN generated theorem list *)
attempt "FINITE_QUADRATIC_CURVE" (fun () -> sthm FINITE_QUADRATIC_CURVE);;
attempt "FIELD_CHAR_NOT2" (fun () -> sthm FIELD_CHAR_NOT2);;
attempt "FIELD_CHAR_NOT3" (fun () -> sthm FIELD_CHAR_NOT3);;
attempt "FIELD_CHAR_NOT23" (fun () -> sthm FIELD_CHAR_NOT23);;
attempt "CAUCHY_GROUP_THEOREM_2" (fun () -> sthm CAUCHY_GROUP_THEOREM_2);;
attempt "GROUP_ADHOC_ORDER_UNIQUE_LEMMA" (fun () -> sthm GROUP_ADHOC_ORDER_UNIQUE_LEMMA);;
attempt "SYMMETRY_LEMMA" (fun () -> sthm SYMMETRY_LEMMA);;
attempt "ASSOCIATIVITY_LEMMA" (fun () -> sthm ASSOCIATIVITY_LEMMA);;
attempt "INTEGER_MOD_RING_ROOT_EXISTS" (fun () -> sthm INTEGER_MOD_RING_ROOT_EXISTS);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
