(* Reference behaviour of equal.ml. Keep in sync with
   equal/equal_ref_test.mbt. *)
let _ = new_type("num",0);;
let _ = new_constant("+", mk_type("fun",[mk_type("num",[]); mk_type("fun",[mk_type("num",[]); mk_type("num",[])])]));;
let _ = parse_as_infix("+",(16,"right"));;
let _ = new_constant("!", parse_type "(A->bool)->bool");;
let _ = parse_as_binder "!";;
let _ = parse_as_binder "\\";;
let _ = parse_as_infix("=",(12,"right"));;
let _ = new_constant("c", parse_type "num");;
let tm s = parse_term s;;
let th name f = attempt name (fun () -> string_of_thm (f ()));;
let t name f = attempt name (fun () -> string_of_term (f ()));;
th "BETA_CONV" (fun () -> BETA_CONV (tm "(\\x:num. x + x) c"));;
th "BETA_CONV_var" (fun () -> BETA_CONV (tm "(\\x:num. x + y) x"));;
th "BETA_CONV_bad" (fun () -> BETA_CONV (tm "(f:num->num) c"));;
th "AP_TERM" (fun () -> AP_TERM (tm "f:num->num") (ASSUME (tm "(x:num) = y")));;
th "AP_TERM_bad" (fun () -> AP_TERM (tm "f:bool->num") (ASSUME (tm "(x:num) = y")));;
th "AP_THM" (fun () -> AP_THM (ASSUME (tm "(f:num->num) = g")) (tm "c"));;
th "SYM" (fun () -> SYM (ASSUME (tm "(x:num) = y + c")));;
th "ALPHA" (fun () -> ALPHA (tm "\\x:num. x + c") (tm "\\y:num. y + c"));;
th "ALPHA_bad" (fun () -> ALPHA (tm "\\x:num. x + c") (tm "\\y:num. c + y"));;
th "ALPHA_CONV" (fun () -> ALPHA_CONV (tm "z:num") (tm "\\x:num. x + c"));;
th "GEN_ALPHA_CONV" (fun () -> GEN_ALPHA_CONV (tm "z:num") (tm "!x:num. x + c = c"));;
th "MK_BINOP" (fun () -> MK_BINOP (tm "(+)") (ASSUME (tm "(a:num) = b"), ASSUME (tm "(c':num) = d")));;
th "THENC" (fun () -> (BETA_CONV THENC BETA_CONV) (tm "(\\x:num. (\\y:num. y + x) c) c"));;
th "ORELSEC" (fun () -> (NO_CONV ORELSEC BETA_CONV) (tm "(\\x:num. x) c"));;
th "REPEATC" (fun () -> REPEATC BETA_CONV (tm "(\\x:num. (\\y:num. y) x) c"));;
th "CHANGED_CONV" (fun () -> CHANGED_CONV ALL_CONV (tm "c"));;
th "TRY_CONV" (fun () -> TRY_CONV BETA_CONV (tm "c"));;
th "FIRST_CONV" (fun () -> FIRST_CONV [NO_CONV; BETA_CONV; ALL_CONV] (tm "(\\x:num. x) c"));;
th "EVERY_CONV" (fun () -> EVERY_CONV [BETA_CONV; ALL_CONV] (tm "(\\x:num. x) c"));;
th "RATOR_CONV" (fun () -> RATOR_CONV (RAND_CONV BETA_CONV) (tm "(\\x:num. x) c + c"));;
th "LAND_CONV" (fun () -> LAND_CONV BETA_CONV (tm "(\\x:num. x) c + c"));;
th "RAND_CONV_bad" (fun () -> RAND_CONV BETA_CONV (tm "c"));;
th "COMB_CONV" (fun () -> COMB_CONV (TRY_CONV BETA_CONV) (tm "(f:num->num) ((\\x:num. x) c)"));;
th "ABS_CONV" (fun () -> ABS_CONV BETA_CONV (tm "\\y:num. (\\x:num. x + y) c"));;
th "ABS_CONV_hyp" (fun () -> ABS_CONV (fun t -> ASSUME (mk_eq(t, tm "c"))) (tm "\\x:num. x + c"));;
th "BINDER_CONV" (fun () -> BINDER_CONV BETA_CONV (tm "!y:num. (\\x:num. x + y) c = c"));;
th "SUB_CONV" (fun () -> SUB_CONV (TRY_CONV BETA_CONV) (tm "(\\x:num. x) c + (\\x:num. x) c"));;
th "BINOP_CONV" (fun () -> BINOP_CONV BETA_CONV (tm "(\\x:num. x) c + (\\x:num. x) c"));;
let nested = tm "(\\f:num->num. f ((\\x:num. x + x) c)) (\\y:num. (\\z:num. z) y)";;
th "ONCE_DEPTH_CONV" (fun () -> ONCE_DEPTH_CONV BETA_CONV nested);;
th "DEPTH_CONV" (fun () -> DEPTH_CONV BETA_CONV nested);;
th "REDEPTH_CONV" (fun () -> REDEPTH_CONV BETA_CONV nested);;
th "TOP_DEPTH_CONV" (fun () -> TOP_DEPTH_CONV BETA_CONV nested);;
th "TOP_SWEEP_CONV" (fun () -> TOP_SWEEP_CONV BETA_CONV nested);;
th "DEPTH_CONV_none" (fun () -> DEPTH_CONV BETA_CONV (tm "c + c"));;
th "DEPTH_BINOP_CONV" (fun () -> DEPTH_BINOP_CONV (tm "(+)") (TRY_CONV BETA_CONV) (tm "(\\x:num. x) c + c + (\\y:num. y + y) c"));;
th "PATH_CONV" (fun () -> PATH_CONV "lr" BETA_CONV (tm "(\\x:num. x) c + c"));;
th "PAT_CONV" (fun () -> PAT_CONV (tm "\\x:num. x + c") BETA_CONV (tm "(\\x:num. x) c + c"));;
th "SYM_CONV" (fun () -> SYM_CONV (tm "(x:num) = y"));;
th "CONV_RULE" (fun () -> CONV_RULE (RAND_CONV BETA_CONV) (ASSUME (tm "(a:num) = (\\x:num. x) c")));;
th "SUBS_CONV" (fun () -> SUBS_CONV [ASSUME (tm "(a:num) = b"); ASSUME (tm "(c:num) = d")] (tm "a + c + (\\a:num. a) b"));;
th "SUBS" (fun () -> SUBS [ASSUME (tm "(a:num) = b")] (ASSUME (tm "a + a = (c:num)")));;
th "BETA_RULE" (fun () -> BETA_RULE (ASSUME (tm "(\\x:num. (\\y:num. y) x) c = c")));;
th "GSYM" (fun () -> GSYM (ASSUME (tm "!x:num. x = c")));;
let cc = CACHE_CONV BETA_CONV;;
th "CACHE_CONV1" (fun () -> cc (tm "(\\x:num. x + x) c"));;
th "CACHE_CONV2" (fun () -> cc (tm "(\\y:num. y + y) c"));;
th "CACHE_CONV3" (fun () -> cc (tm "(\\x:num. x + x) c"));;
t "mk_primed_var" (fun () -> mk_primed_var [tm "x:num"; tm "x':num"] (tm "x:bool"));;
t "mk_primed_var_const" (fun () -> mk_primed_var [] (tm "c':bool") |> fun v -> mk_primed_var [] (mk_var("c", bool_ty)));;
t "lhand" (fun () -> lhand (tm "(a:num) + b"));;
t "genvar_after" (fun () -> genvar bool_ty);;
th "COMB2_CONV_order" (fun () -> COMB2_CONV (fun _ -> failwith "left") (fun _ -> failwith "right") (tm "(f:num->num) c"));;
th "BINOP_CONV_order" (fun () -> BINOP_CONV (fun t -> failwith (string_of_term t)) (tm "a + (b:num)"));;
th "BINOP2_CONV_order" (fun () -> BINOP2_CONV (fun _ -> failwith "left") (fun _ -> failwith "right") (tm "a + (b:num)"));;
th "COMB_CONV_genvar" (fun () -> COMB_CONV (fun t -> let v = genvar (type_of t) in failwith (fst(dest_var v))) (tm "(f:num->num) c"));;
