(* Load-fidelity test for Examples/lucas_lehmer.ml (translated by tools/translator). Keep
   in sync with examples/lucas_lehmer/lucas_lehmer_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "Library/iter.ml";;
#use "Library/prime.ml";;
#use "Library/pocklington.ml";;
#use "Library/floor.ml";;
#use "Library/wo.ml";;
#use "Library/card.ml";;
#use "Multivariate/misc.ml";;
#use "Library/products.ml";;
#use "Multivariate/metric.ml";;
#use "Library/frag.ml";;
#use "Library/grouptheory.ml";;
#use "Multivariate/homology.ml";;
#use "Library/matroids.ml";;
#use "Multivariate/vectors.ml";;
#use "100/sqrt.ml";;
start_trace ();;
#use "Examples/lucas_lehmer.ml";;
show_trace "Examples/lucas_lehmer";;
(* BEGIN generated theorem list *)
attempt "REAL_POW_ITER" (fun () -> sthm REAL_POW_ITER);;
attempt "llseq" (fun () -> sthm llseq);;
attempt "LLSEQ_CLOSEDFORM" (fun () -> sthm LLSEQ_CLOSEDFORM);;
attempt "LUCAS_LEHMER" (fun () -> sthm LUCAS_LEHMER);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
