(* Load-fidelity test for Examples/prover9.ml (translated by tools/translator). Keep
   in sync with examples/prover9/prover9_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
start_trace ();;
#use "Examples/prover9.ml";;
show_trace "Examples/prover9";;
(* BEGIN generated theorem list *)
attempt "FRIEND_0" (fun () -> sthm FRIEND_0);;
attempt "FRIEND_1" (fun () -> sthm FRIEND_1);;
attempt "LOS" (fun () -> sthm LOS);;
attempt "CONWAY_1" (fun () -> sthm CONWAY_1);;
attempt "CONWAY_2" (fun () -> sthm CONWAY_2);;
attempt "ECKMAN_HILTON_1" (fun () -> sthm ECKMAN_HILTON_1);;
attempt "ECKMAN_HILTON_2" (fun () -> sthm ECKMAN_HILTON_2);;
attempt "ECKMAN_HILTON_3" (fun () -> sthm ECKMAN_HILTON_3);;
attempt "ECKMAN_HILTON_4" (fun () -> sthm ECKMAN_HILTON_4);;
attempt "DOUBLE_DISTRIB" (fun () -> sthm DOUBLE_DISTRIB);;
attempt "MOORE_PENROSE_PSEUDOINVERSE_UNIQUE" (fun () -> sthm MOORE_PENROSE_PSEUDOINVERSE_UNIQUE);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
