(* Load-fidelity test for Examples/holby.ml (translated by tools/translator). Keep
   in sync with examples/holby/holby_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
start_trace ();;
#use "Examples/holby.ml";;
show_trace "Examples/holby";;
(* BEGIN generated theorem list *)
attempt "prop_1" (fun () -> sthm prop_1);;
attempt "prop_2" (fun () -> sthm prop_2);;
attempt "prop_3" (fun () -> sthm prop_3);;
attempt "prop_4" (fun () -> sthm prop_4);;
attempt "prop_5" (fun () -> sthm prop_5);;
attempt "prop_6" (fun () -> sthm prop_6);;
attempt "prop_7" (fun () -> sthm prop_7);;
attempt "prop_8" (fun () -> sthm prop_8);;
attempt "prop_9" (fun () -> sthm prop_9);;
attempt "prop_10" (fun () -> sthm prop_10);;
attempt "prop_11" (fun () -> sthm prop_11);;
attempt "prop_12" (fun () -> sthm prop_12);;
attempt "prop_13" (fun () -> sthm prop_13);;
attempt "prop_14" (fun () -> sthm prop_14);;
attempt "prop_15" (fun () -> sthm prop_15);;
attempt "prop_16" (fun () -> sthm prop_16);;
attempt "prop_17" (fun () -> sthm prop_17);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
