(* Load-fidelity test for Examples/mccarthy.ml (translated by tools/translator). Keep
   in sync with examples/mccarthy/mccarthy_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
start_trace ();;
#use "Examples/mccarthy.ml";;
show_trace "Examples/mccarthy";;
(* BEGIN generated theorem list *)
attempt "string_INDUCT" (fun () -> sthm string_INDUCT);;
attempt "string_RECURSION" (fun () -> sthm string_RECURSION);;
attempt "exp_INDUCT" (fun () -> sthm exp_INDUCT);;
attempt "exp_RECURSION" (fun () -> sthm exp_RECURSION);;
attempt "E_DEF" (fun () -> sthm E_DEF);;
attempt "cell_INDUCT" (fun () -> sthm cell_INDUCT);;
attempt "cell_RECURSION" (fun () -> sthm cell_RECURSION);;
attempt "inst_INDUCT" (fun () -> sthm inst_INDUCT);;
attempt "inst_RECURSION" (fun () -> sthm inst_RECURSION);;
attempt "update_def" (fun () -> sthm update_def);;
attempt "S_DEF" (fun () -> sthm S_DEF);;
attempt "S'_DEF" (fun () -> sthm S'_DEF);;
attempt "C_DEF" (fun () -> sthm C_DEF);;
attempt "cellth" (fun () -> sthm cellth);;
attempt "S'_APPEND" (fun () -> sthm S'_APPEND);;
attempt "UPDATE_DIFFERENT" (fun () -> sthm UPDATE_DIFFERENT);;
attempt "UPDATE_SAME" (fun () -> sthm UPDATE_SAME);;
attempt "CORRECTNESS_THEOREM" (fun () -> sthm CORRECTNESS_THEOREM);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
