(* Load-fidelity test for Examples/cong.ml (translated by tools/translator). Keep
   in sync with examples/cong/cong_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
start_trace ();;
#use "Examples/cong.ml";;
show_trace "Examples/cong";;
(* BEGIN generated theorem list *)
attempt "CONG" (fun () -> sthm CONG);;
attempt "CONG_MOD_0" (fun () -> sthm CONG_MOD_0);;
attempt "CONG_REFL" (fun () -> sthm CONG_REFL);;
attempt "CONG_SYM" (fun () -> sthm CONG_SYM);;
attempt "CONG_TRANS" (fun () -> sthm CONG_TRANS);;
attempt "CONG_ADD" (fun () -> sthm CONG_ADD);;
attempt "CONG_NEG" (fun () -> sthm CONG_NEG);;
attempt "CONG_SUB" (fun () -> sthm CONG_SUB);;
attempt "CONG_MUL" (fun () -> sthm CONG_MUL);;
attempt "CONG_MOD_NEG" (fun () -> sthm CONG_MOD_NEG);;
attempt "CONG_MOD_ABS" (fun () -> sthm CONG_MOD_ABS);;
attempt "CONG_MULTIPLE" (fun () -> sthm CONG_MULTIPLE);;
attempt "CONG_SELF" (fun () -> sthm CONG_SELF);;
attempt "CONG_SELF_ABS" (fun () -> sthm CONG_SELF_ABS);;
attempt "CONG_MOD_1" (fun () -> sthm CONG_MOD_1);;
attempt "CONG_REP_POS_POS" (fun () -> sthm CONG_REP_POS_POS);;
attempt "CONG_REP_POS" (fun () -> sthm CONG_REP_POS);;
attempt "CONG_REP_MIN" (fun () -> sthm CONG_REP_MIN);;
attempt "CONG_REP_MIN_ABS" (fun () -> sthm CONG_REP_MIN_ABS);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
