(* Load-fidelity test for Examples/dlo.ml (translated by tools/translator). Keep
   in sync with examples/dlo/dlo_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
start_trace ();;
#use "Examples/dlo.ml";;
show_trace "Examples/dlo";;
(* BEGIN generated theorem list *)
attempt "MINL" (fun () -> sthm MINL);;
attempt "MAXL" (fun () -> sthm MAXL);;
attempt "MAX_LT" (fun () -> sthm MAX_LT);;
attempt "MIN_GT" (fun () -> sthm MIN_GT);;
attempt "ALL_LT_LEMMA" (fun () -> sthm ALL_LT_LEMMA);;
attempt "ALL_GT_LEMMA" (fun () -> sthm ALL_GT_LEMMA);;
attempt "REAL_DENSE" (fun () -> sthm REAL_DENSE);;
attempt "REAL_LT_EXISTS" (fun () -> sthm REAL_LT_EXISTS);;
attempt "REAL_GT_EXISTS" (fun () -> sthm REAL_GT_EXISTS);;
attempt "PROFORMA_LEFT" (fun () -> sthm PROFORMA_LEFT);;
attempt "PROFORMA_RIGHT" (fun () -> sthm PROFORMA_RIGHT);;
attempt "PROFORMA_BOTH" (fun () -> sthm PROFORMA_BOTH);;
attempt "forall_thm" (fun () -> sthm forall_thm);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
