(* Load-fidelity test for Examples/zolotarev.ml (translated by tools/translator). Keep
   in sync with examples/zolotarev/zolotarev_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "Library/integer.ml";;
#use "Library/isum.ml";;
#use "Library/binomial.ml";;
#use "Library/iter.ml";;
#use "Library/prime.ml";;
#use "Library/pocklington.ml";;
#use "Library/products.ml";;
#use "Library/multiplicative.ml";;
#use "Library/primitive.ml";;
#use "Library/jacobi.ml";;
#use "Library/permutations.ml";;
start_trace ();;
#use "Examples/zolotarev.ml";;
show_trace "Examples/zolotarev";;
(* BEGIN generated theorem list *)
attempt "zolotarev" (fun () -> sthm zolotarev);;
attempt "PERMUTES_ZOLOTAREV" (fun () -> sthm PERMUTES_ZOLOTAREV);;
attempt "PERMUTES_ZOLOTAREV_ALT" (fun () -> sthm PERMUTES_ZOLOTAREV_ALT);;
attempt "PERMUTATION_ZOLOTAREV" (fun () -> sthm PERMUTATION_ZOLOTAREV);;
attempt "ZOLATAREV_MOD" (fun () -> sthm ZOLATAREV_MOD);;
attempt "ZOLOTAREV_CONG" (fun () -> sthm ZOLOTAREV_CONG);;
attempt "zolotarevu" (fun () -> sthm zolotarevu);;
attempt "PERMUTES_ZOLOTAREVU" (fun () -> sthm PERMUTES_ZOLOTAREVU);;
attempt "PERMUTATION_ZOLOTAREVU" (fun () -> sthm PERMUTATION_ZOLOTAREVU);;
attempt "ZOLATAREVU_MOD" (fun () -> sthm ZOLATAREVU_MOD);;
attempt "ZOLOTAREVU_PRIMITIVE" (fun () -> sthm ZOLOTAREVU_PRIMITIVE);;
attempt "ZOLATAREV_EQ_ZOLATAREVU" (fun () -> sthm ZOLATAREV_EQ_ZOLATAREVU);;
attempt "ZOLOTAREV_1" (fun () -> sthm ZOLOTAREV_1);;
attempt "JACOBI_EQ_ZOLOTAREV_PRIMEPOW" (fun () -> sthm JACOBI_EQ_ZOLOTAREV_PRIMEPOW);;
attempt "JACOBI_EQ_ZOLOTAREV" (fun () -> sthm JACOBI_EQ_ZOLOTAREV);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
