(* Load-fidelity test for Examples/gcdrecurrence.ml (translated by tools/translator). Keep
   in sync with examples/gcdrecurrence/gcdrecurrence_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "Library/prime.ml";;
#use "Library/integer.ml";;
start_trace ();;
#use "Examples/gcdrecurrence.ml";;
show_trace "Examples/gcdrecurrence";;
(* BEGIN generated theorem list *)
attempt "INDUCT_SPECIAL" (fun () -> sthm INDUCT_SPECIAL);;
attempt "INT_DIVISORS_RECURRENCE" (fun () -> sthm INT_DIVISORS_RECURRENCE);;
attempt "INT_GCD_RECURRENCE" (fun () -> sthm INT_GCD_RECURRENCE);;
attempt "GCD_RECURRENCE" (fun () -> sthm GCD_RECURRENCE);;
attempt "DIVISORS_RECURRENCE" (fun () -> sthm DIVISORS_RECURRENCE);;
attempt "GCD_MERSENNE" (fun () -> sthm GCD_MERSENNE);;
attempt "DIVIDES_MERSENNE" (fun () -> sthm DIVIDES_MERSENNE);;
attempt "fib" (fun () -> sthm fib);;
attempt "GCD_FIB" (fun () -> sthm GCD_FIB);;
attempt "FIB_EQ_0" (fun () -> sthm FIB_EQ_0);;
attempt "FIB_INCREASES_LE" (fun () -> sthm FIB_INCREASES_LE);;
attempt "FIB_INCREASES_LT" (fun () -> sthm FIB_INCREASES_LT);;
attempt "FIB_EQ_1" (fun () -> sthm FIB_EQ_1);;
attempt "DIVIDES_FIB" (fun () -> sthm DIVIDES_FIB);;
attempt "pellx" (fun () -> sthm pellx);;
attempt "pelly" (fun () -> sthm pelly);;
attempt "PELLY_INCREASES" (fun () -> sthm PELLY_INCREASES);;
attempt "GCD_PELLY" (fun () -> sthm GCD_PELLY);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
