(* Load-fidelity test for GL/decid.ml (translated by tools/translator). Keep
   in sync with gl/decid/decid_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "Library/wo.ml";;
#use "Library/card.ml";;
#use "Library/rstc.ml";;
#use "GL/misc.ml";;
#use "GL/modal.ml";;
#use "GL/gl.ml";;
#use "GL/completeness.ml";;
#use "GL/k4lr.ml";;
start_trace ();;
#use "GL/decid.ml";;
show_trace "GL/decid";;
(* BEGIN generated theorem list *)
attempt "HOLDS_NNFC_UNFOLD" (fun () -> sthm HOLDS_NNFC_UNFOLD);;
attempt "COMPLETENESS_NUM" (fun () -> sthm COMPLETENESS_NUM);;
attempt "GL_second_incompleteness_theorem" (fun () -> sthm GL_second_incompleteness_theorem);;
attempt "GL_PA_ignorance" (fun () -> sthm GL_PA_ignorance);;
attempt "GL_PA_undecidability_of_consistency" (fun () -> sthm GL_PA_undecidability_of_consistency);;
attempt "GL_undecidability_of_Godels_formula" (fun () -> sthm GL_undecidability_of_Godels_formula);;
attempt "GL_reflection_and_iterated_consistency" (fun () -> sthm GL_reflection_and_iterated_consistency);;
attempt "GL_Godel_sentence_equiconsistent_consistency" (fun () -> sthm GL_Godel_sentence_equiconsistent_consistency);;
attempt "GL_arithmetical_fixpoint" (fun () -> sthm GL_arithmetical_fixpoint);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
