(* Load-fidelity test for grobner.ml (translated by tools/translator). Keep
   in sync with grobner/grobner_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
start_trace ();;
#use "grobner.ml";;
show_trace "grobner";;
(* BEGIN generated theorem list *)
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (length (definitions())));;
(* BEGIN EXTRA *)
attempt "ring_sq" (fun () -> sthm (NUM_RING (tm "(x + y) EXP 2 = x EXP 2 + 2 * x * y + y EXP 2")));;
attempt "ring_comm" (fun () -> sthm (NUM_RING (tm "a * b + c = c + b * a")));;
attempt "ring_impl" (fun () -> sthm (NUM_RING (tm "x = y ==> x * z = y * z")));;
attempt "ring_cancel" (fun () -> sthm (NUM_RING (tm "a + b = a + c ==> b = c")));;
attempt "ring_false" (fun () -> sthm (NUM_RING (tm "x * x = 2")));;
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
