(* Load-fidelity test for IEEE/float.ml (translated by tools/translator). Keep
   in sync with ieee/float/float_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "IEEE/common.hl";;
#use "IEEE/fixed.hl";;
#use "IEEE/fixed_thms.hl";;
start_trace ();;
#use "IEEE/float.hl";;
show_trace "IEEE/float";;
(* BEGIN generated theorem list *)
attempt "is_valid_flformat" (fun () -> sthm is_valid_flformat);;
attempt "flformat_typbij" (fun () -> sthm flformat_typbij);;
attempt "flr" (fun () -> sthm flr);;
attempt "flp" (fun () -> sthm flp);;
attempt "is_frac_and_exp" (fun () -> sthm is_frac_and_exp);;
attempt "is_float" (fun () -> sthm is_float);;
attempt "to_fformat" (fun () -> sthm to_fformat);;
attempt "greatest_e" (fun () -> sthm greatest_e);;
attempt "greatest_m" (fun () -> sthm greatest_m);;
attempt "greatest_r" (fun () -> sthm greatest_r);;
attempt "flround" (fun () -> sthm flround);;
attempt "fl_eps" (fun () -> sthm fl_eps);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
