(* Load-fidelity test for IEEE/ieee.ml (translated by tools/translator). Keep
   in sync with ieee/ieee/ieee_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "IEEE/common.hl";;
#use "IEEE/fixed.hl";;
#use "IEEE/fixed_thms.hl";;
#use "IEEE/float.hl";;
#use "IEEE/float_thms.hl";;
start_trace ();;
#use "IEEE/ieee.hl";;
show_trace "IEEE/ieee";;
(* BEGIN generated theorem list *)
attempt "is_valid_ieee_format" (fun () -> sthm is_valid_ieee_format);;
attempt "ieee_format_typbij" (fun () -> sthm ieee_format_typbij);;
attempt "ieee_r" (fun () -> sthm ieee_r);;
attempt "ieee_p" (fun () -> sthm ieee_p);;
attempt "ieee_emin" (fun () -> sthm ieee_emin);;
attempt "ieee_emax" (fun () -> sthm ieee_emax);;
attempt "ieee_to_fformat" (fun () -> sthm ieee_to_fformat);;
attempt "ieee_to_flformat" (fun () -> sthm ieee_to_flformat);;
attempt "max_ieee" (fun () -> sthm max_ieee);;
attempt "ieee_threshold" (fun () -> sthm ieee_threshold);;
attempt "is_ieee_pinf" (fun () -> sthm is_ieee_pinf);;
attempt "is_ieee_ninf" (fun () -> sthm is_ieee_ninf);;
attempt "is_ieee" (fun () -> sthm is_ieee);;
attempt "ieee_exp" (fun () -> sthm ieee_exp);;
attempt "ieee_round" (fun () -> sthm ieee_round);;
attempt "ieee_eps" (fun () -> sthm ieee_eps);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
