(* Load-fidelity test for IEEE/fixed.ml (translated by tools/translator). Keep
   in sync with ieee/fixed/fixed_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "IEEE/common.hl";;
start_trace ();;
#use "IEEE/fixed.hl";;
show_trace "IEEE/fixed";;
(* BEGIN generated theorem list *)
attempt "is_valid_fformat" (fun () -> sthm is_valid_fformat);;
attempt "fformat_typbij" (fun () -> sthm fformat_typbij);;
attempt "fr" (fun () -> sthm fr);;
attempt "fp" (fun () -> sthm fp);;
attempt "fe" (fun () -> sthm fe);;
attempt "is_frac" (fun () -> sthm is_frac);;
attempt "ff" (fun () -> sthm ff);;
attempt "is_fixed" (fun () -> sthm is_fixed);;
attempt "fulp" (fun () -> sthm fulp);;
attempt "finf" (fun () -> sthm finf);;
attempt "fixed" (fun () -> sthm fixed);;
attempt "is_lb" (fun () -> sthm is_lb);;
attempt "is_glb" (fun () -> sthm is_glb);;
attempt "is_ub" (fun () -> sthm is_ub);;
attempt "is_lub" (fun () -> sthm is_lub);;
attempt "glb" (fun () -> sthm glb);;
attempt "lub" (fun () -> sthm lub);;
attempt "roundmode_INDUCT" (fun () -> sthm roundmode_INDUCT);;
attempt "roundmode_RECURSION" (fun () -> sthm roundmode_RECURSION);;
attempt "fround" (fun () -> sthm fround);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
