(* Load-fidelity test for IsabelleLight/meta_rules.ml (translated by tools/translator). Keep
   in sync with isabellelight/meta_rules/meta_rules_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "IsabelleLight/support.ml";;
#use "IsabelleLight/new_tactics.ml";;
start_trace ();;
#use "IsabelleLight/meta_rules.ml";;
show_trace "IsabelleLight/meta_rules";;
(* BEGIN generated theorem list *)
attempt "MIMP_DEF" (fun () -> sthm MIMP_DEF);;
attempt "MIMP_THM" (fun () -> sthm MIMP_THM);;
attempt "conjI" (fun () -> sthm conjI);;
attempt "conjunct1" (fun () -> sthm conjunct1);;
attempt "conjunct2" (fun () -> sthm conjunct2);;
attempt "conjE" (fun () -> sthm conjE);;
attempt "disjI1" (fun () -> sthm disjI1);;
attempt "disjI2" (fun () -> sthm disjI2);;
attempt "disjE" (fun () -> sthm disjE);;
attempt "impI" (fun () -> sthm impI);;
attempt "impE" (fun () -> sthm impE);;
attempt "mp" (fun () -> sthm mp);;
attempt "iffI" (fun () -> sthm iffI);;
attempt "iffE" (fun () -> sthm iffE);;
attempt "allE" (fun () -> sthm allE);;
attempt "exI" (fun () -> sthm exI);;
attempt "notI" (fun () -> sthm notI);;
attempt "notE" (fun () -> sthm notE);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
