(* Load-fidelity test for Jordan/num_ext_gcd.ml (translated by tools/translator). Keep
   in sync with jordan/num_ext_gcd/num_ext_gcd_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "Library/analysis.ml";;
#use "Library/transc.ml";;
#use "Examples/polylog.ml";;
#use "Jordan/tactics_refine.ml";;
#use "Jordan/lib_ext.ml";;
#use "Jordan/tactics_fix.ml";;
#use "Jordan/parse_ext_override_interface.ml";;
#use "Jordan/tactics_ext.ml";;
start_trace ();;
#use "Jordan/num_ext_gcd.ml";;
show_trace "Jordan/num_ext_gcd";;
(* BEGIN generated theorem list *)
attempt "DIVIDE" (fun () -> sthm DIVIDE);;
attempt "DIVIDE_DIVIDE" (fun () -> sthm DIVIDE_DIVIDE);;
attempt "DIVIDE_EQ" (fun () -> sthm DIVIDE_EQ);;
attempt "DIVIDE_SUM" (fun () -> sthm DIVIDE_SUM);;
attempt "DIVIDE_SUMMAND" (fun () -> sthm DIVIDE_SUMMAND);;
attempt "DIVIDE_PROD" (fun () -> sthm DIVIDE_PROD);;
attempt "DIVIDE_PROD2" (fun () -> sthm DIVIDE_PROD2);;
attempt "GCD" (fun () -> sthm GCD);;
attempt "gcd_certificate" (fun () -> sthm gcd_certificate);;
attempt "divide" (fun () -> sthm divide);;
attempt "gcd" (fun () -> sthm gcd);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
