(* Load-fidelity test for Jordan/num_ext_nabs.ml (translated by tools/translator). Keep
   in sync with jordan/num_ext_nabs/num_ext_nabs_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "Library/analysis.ml";;
#use "Library/transc.ml";;
#use "Examples/polylog.ml";;
#use "Jordan/tactics_refine.ml";;
#use "Jordan/lib_ext.ml";;
#use "Jordan/tactics_fix.ml";;
#use "Jordan/parse_ext_override_interface.ml";;
#use "Jordan/tactics_ext.ml";;
#use "Jordan/num_ext_gcd.ml";;
start_trace ();;
#use "Jordan/num_ext_nabs.ml";;
show_trace "Jordan/num_ext_nabs";;
(* BEGIN generated theorem list *)
attempt "INT_NUM" (fun () -> sthm INT_NUM);;
attempt "INT_NUM_REAL" (fun () -> sthm INT_NUM_REAL);;
attempt "INT_IS_INT" (fun () -> sthm INT_IS_INT);;
attempt "INT_OF_NUM_DEST" (fun () -> sthm INT_OF_NUM_DEST);;
attempt "INT_REP" (fun () -> sthm INT_REP);;
attempt "INT_REP2" (fun () -> sthm INT_REP2);;
attempt "nabs" (fun () -> sthm nabs);;
attempt "NABS_POS" (fun () -> sthm NABS_POS);;
attempt "NABS_NEG" (fun () -> sthm NABS_NEG);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
