(* Keep this file in sync with kernel/kernel_ref_test.mbt. *)
let a = mk_vartype "A" and b = mk_vartype "B";;
let fn x y = mk_type("fun",[x;y]);;
let _ = new_type("ind",0);;
let ind = mk_type("ind",[]);;
attempt "tyvars" (fun () -> slist sty (tyvars (fn a (fn b a))));;
attempt "mk_type_bad" (fun () -> sty (mk_type("fun",[a])));;
attempt "mk_type_undef" (fun () -> sty (mk_type("foo",[])));;
attempt "new_type_dup" (fun () -> new_type("ind",0); "ok");;
attempt "type_subst" (fun () -> sty (type_subst [ind,a; a,b] (fn a (fn b a))));;
let x = mk_var("x",a) and y = mk_var("y",a) and z = mk_var("z",a);;
let f = mk_var("f",fn a (fn a a)) and g = mk_var("g",fn a a);;
let app f x = mk_comb(f,x);;
let eq l r = mk_comb(mk_comb(mk_const("=",[type_of l,aty]),l),r);;
attempt "mk_comb_bad" (fun () -> stm (mk_comb(x,y)));;
attempt "mk_abs_bad" (fun () -> stm (mk_abs(g,x)));;
attempt "mk_const_bad" (fun () -> stm (mk_const("nope",[])));;
let t1 = app (app f x) (app g y);;
attempt "frees" (fun () -> slist stm (frees (mk_abs(x, app (app f (app g z)) (app (app f x) y)))));;
attempt "freesl" (fun () -> slist stm (freesl [app g z; t1; x]));;
attempt "type_vars_in_term" (fun () -> slist sty (type_vars_in_term (mk_abs(mk_var("u",b), app g x))));;
attempt "variant" (fun () -> stm (variant [x; mk_var("x'",a); app g (mk_var("x''",a))] x));;
attempt "vsubst_capture" (fun () -> stm (vsubst [y,x] (mk_abs(y, app (app f x) y))));;
attempt "vsubst_bad" (fun () -> stm (vsubst [mk_var("u",b),x] x));;
attempt "vsubst_bound" (fun () -> stm (vsubst [z,x] (mk_abs(x, app g x))));;
let xb = mk_var("x",b);;
let fab = mk_var("f",fn a (fn b a));;
let tclash = mk_abs(x, app (app fab x) xb);;
attempt "inst_clash" (fun () -> stm (inst [b,a] tclash));;
attempt "inst_simple" (fun () -> stm (inst [ind,a] (mk_abs(x, app g x))));;
attempt "alphaorder" (fun () -> slist string_of_int
  [alphaorder (mk_abs(x,x)) (mk_abs(y,y)); alphaorder x y; alphaorder y x;
   alphaorder (mk_const("=",[])) x; alphaorder (app g x) (mk_abs(x,x));
   alphaorder (mk_abs(x,y)) (mk_abs(y,x))]);;
attempt "compare" (fun () -> slist string_of_int
  [compare "b" "aa"; compare "" "a"; compare "ab" "a";
   compare x (mk_const("=",[])); compare (app g x) (mk_abs(x,x));
   compare (Tyvar "Z") ind; compare (fn a a) (fn a b)]);;
let p = mk_var("p",bool_ty) and q = mk_var("q",bool_ty) and r = mk_var("r",bool_ty);;
attempt "REFL" (fun () -> sthm (REFL t1));;
attempt "ASSUME" (fun () -> sthm (ASSUME p));;
attempt "ASSUME_bad" (fun () -> sthm (ASSUME x));;
let hpq = ASSUME (eq p q) and hqr = ASSUME (eq q r);;
attempt "TRANS" (fun () -> sthm (TRANS hpq hqr));;
attempt "TRANS_bad" (fun () -> sthm (TRANS hqr hpq));;
attempt "MK_COMB" (fun () -> sthm (MK_COMB(ASSUME (eq g g), ASSUME (eq x y))));;
attempt "MK_COMB_bad" (fun () -> sthm (MK_COMB(ASSUME (eq x y), ASSUME (eq x y))));;
attempt "ABS" (fun () -> sthm (ABS z (ASSUME (eq x y))));;
attempt "ABS_bad" (fun () -> sthm (ABS x (ASSUME (eq x y))));;
attempt "BETA" (fun () -> sthm (BETA (app (mk_abs(x, app g x)) x)));;
attempt "BETA_bad" (fun () -> sthm (BETA (app (mk_abs(x, app g x)) y)));;
attempt "EQ_MP" (fun () -> sthm (EQ_MP hpq (ASSUME p)));;
attempt "EQ_MP_bad" (fun () -> sthm (EQ_MP hpq (ASSUME q)));;
attempt "DEDUCT_ANTISYM" (fun () -> sthm (DEDUCT_ANTISYM_RULE (EQ_MP hpq (ASSUME p)) (ASSUME r)));;
let hx = ASSUME (eq (mk_abs(x, app g x)) g);;
let hy = ASSUME (eq (mk_abs(y, app g y)) g);;
attempt "TRANS_alpha_mismatch" (fun () -> sthm (TRANS (TRANS hpq hqr) (EQ_MP (ASSUME (eq r r)) (ASSUME r))));;
attempt "hyp_alpha_dedup" (fun () -> sthm (DEDUCT_ANTISYM_RULE hx hy));;
attempt "INST_TYPE" (fun () -> sthm (INST_TYPE [ind,a] (ASSUME (eq (app g x) y))));;
attempt "INST" (fun () -> sthm (INST [z,x; x,y] (DEDUCT_ANTISYM_RULE (ASSUME (eq x y)) (ASSUME (eq y z)))));;
attempt "INST_bad" (fun () -> sthm (INST [p,x] (ASSUME (eq x y))));;
attempt "INST_merge" (fun () -> sthm (INST [x,y] (TRANS (ASSUME (eq x y)) (ASSUME (eq y x)))));;
attempt "new_axiom_bad" (fun () -> sthm (new_axiom x));;
attempt "new_axiom" (fun () -> sthm (new_axiom (eq p p)));;
attempt "axioms" (fun () -> slist sthm (axioms()));;
attempt "def_not_closed" (fun () -> sthm (new_basic_definition (eq (mk_var("c",a)) (app g x))));;
attempt "def_tyvars" (fun () -> sthm (new_basic_definition (eq (mk_var("c",bool_ty)) (eq (mk_abs(x,x)) (mk_abs(x,x))))));;
attempt "def" (fun () -> sthm (new_basic_definition (eq (mk_var("ID",fn a a)) (mk_abs(x,x)))));;
attempt "def_again" (fun () -> sthm (new_basic_definition (eq (mk_const("ID",[])) (mk_abs(x,x)))));;
attempt "def_dup_var" (fun () -> sthm (new_basic_definition (eq (mk_var("ID",fn a a)) (mk_abs(x,x)))));;
attempt "definitions" (fun () -> slist sthm (definitions()));;
let sym th = let l,_ = dest_eq (concl th) in
  EQ_MP (MK_COMB(MK_COMB(REFL (rator (rator (concl th))), th), REFL l)) (REFL l);;
let fba = fn b a;;
let v = mk_var("v",fba) and w = mk_var("w",fba);;
let pred = mk_abs(v, eq v v);;
let pw = EQ_MP (sym (BETA (app pred v))) (REFL v);;
attempt "sym" (fun () -> sthm (sym (ASSUME (eq x y))));;
attempt "tydef_hyp" (fun () -> let th1,_ = new_basic_type_definition "t1" ("mk","dest") (ASSUME p) in sthm th1);;
attempt "tydef_noncomb" (fun () -> let th1,_ = new_basic_type_definition "t1" ("mk","dest") (REFL p) in sthm th1);;
attempt "tydef_const_used" (fun () -> let th1,_ = new_basic_type_definition "t1" ("ID","dest") pw in sthm th1);;
attempt "tydef_open" (fun () -> let th1,_ = new_basic_type_definition "t1" ("mk","dest")
  (ASSUME (app (mk_abs(v, eq v w)) v)) in sthm th1);;
attempt "tydef_type_used" (fun () -> let th1,_ = new_basic_type_definition "ind" ("mk1","dest1") pw in sthm th1);;
attempt "tydef" (fun () -> let th1,th2 = new_basic_type_definition "t1" ("mk","dest") pw in
  sthm th1 ^ " ;; " ^ sthm th2);;
attempt "types" (fun () -> slist (fun (s,n) -> s ^ "/" ^ string_of_int n) (types()));;
attempt "constants" (fun () -> slist (fun (s,ty) -> s ^ ":" ^ sty ty) (constants()));;
attempt "definitions" (fun () -> slist sthm (definitions()));;
