(* Reference behaviour of lib.ml, including callback order.
   Keep in sync with lib/lib_ref_test.mbt. *)
let log = ref [];;
let note s = log := s :: !log;;
let flush name = out (name ^ " calls: " ^ String.concat " " (rev !log)); log := [];;
let si = string_of_int;;
let il l = "[" ^ String.concat ";" (map si l) ^ "]";;
let sl l = "[" ^ String.concat ";" l ^ "]";;
let tr name f = attempt name f; flush name;;
let l5 = [3;1;4;1;5];;
tr "map" (fun () -> il (map (fun x -> note (si x); x * 2) l5));;
tr "filter" (fun () -> il (filter (fun x -> note (si x); x > 1) l5));;
tr "partition" (fun () -> let a,b = partition (fun x -> note (si x); x > 2) l5 in il a ^ il b);;
tr "mapfilter" (fun () -> il (mapfilter (fun x -> note (si x); if x = 1 then failwith "no" else x) l5));;
tr "mapi" (fun () -> il (mapi (fun i x -> note (si i); i * x) l5));;
tr "map2" (fun () -> il (map2 (fun x y -> note (si x); x + y) [1;2;3] [4;5;6]));;
tr "map2_bad" (fun () -> il (map2 (fun x y -> note (si x); x + y) [1;2;3] [4;5]));;
tr "itlist" (fun () -> si (itlist (fun x a -> note (si x); x - a) l5 0));;
tr "rev_itlist" (fun () -> si (rev_itlist (fun x a -> note (si x); x - a) l5 0));;
tr "end_itlist" (fun () -> si (end_itlist (fun x a -> note (si x); x - a) l5));;
tr "end_itlist_empty" (fun () -> si (end_itlist (fun x a -> x - a) []));;
tr "itlist2" (fun () -> si (itlist2 (fun x y a -> note (si x); x * y - a) [1;2;3] [4;5;6] 0));;
tr "itlist2_bad" (fun () -> si (itlist2 (fun x y a -> note (si x); x * y - a) [1;2;3] [4;5] 0));;
tr "rev_itlist2_bad" (fun () -> si (rev_itlist2 (fun x y a -> note (si x); x * y - a) [1;2;3] [4;5] 0));;
tr "allpairs" (fun () -> sl (allpairs (fun x y -> note (si x ^ si y); si x ^ si y) [1;2] [3;4;5]));;
tr "sort" (fun () -> il (sort (fun x y -> note (si x ^ "<=" ^ si y); x <= y) l5));;
tr "sort_partial" (fun () -> il (sort (fun x y -> x mod 3 <= y mod 3) [5;3;9;1;4;7;2]));;
tr "mergesort" (fun () -> il (mergesort (fun x y -> note (si x ^ si y); x <= y) l5));;
tr "setify" (fun () -> sl (setify ["b";"aa";"a";"b";"";"ab"]));;
tr "uniq" (fun () -> il (uniq [1;1;2;3;3;3;1]));;
tr "union" (fun () -> il (union [1;2;3;2] [3;4]));;
tr "unions" (fun () -> il (unions [[1;2];[2;3];[4;1]]));;
tr "subtract" (fun () -> il (subtract [1;2;3;2;4] [2]));;
tr "intersect" (fun () -> il (intersect [1;2;3;2;4] [2;4;5]));;
tr "striplist" (fun () -> il (striplist (fun x -> note (si x); if x < 2 then failwith "leaf" else (x/2, x - x/2)) 7));;
tr "splitlist" (fun () -> let l,r = splitlist (fun x -> if x = 0 then failwith "z" else (x, x-1)) 3 in il l ^ si r);;
tr "rev_splitlist" (fun () -> let r,l = rev_splitlist (fun x -> if x = 0 then failwith "z" else (x-1, x)) 3 in si r ^ il l);;
tr "nsplit" (fun () -> let l,r = nsplit (fun x -> (x, x+1)) ["a";"b"] 10 in il l ^ si r);;
tr "chop_list" (fun () -> let a,b = chop_list 2 l5 in il a ^ il b);;
tr "chop_list_bad" (fun () -> let a,b = chop_list 6 l5 in il a ^ il b);;
tr "chop_list_neg" (fun () -> let a,b = chop_list (-1) l5 in il a ^ il b);;
tr "range" (fun () -> il (3--6) ^ il (6--3));;
tr "replicate" (fun () -> il (replicate 7 3));;
tr "el" (fun () -> si (el 2 l5));;
tr "el_bad" (fun () -> si (el 9 l5));;
tr "last_butlast" (fun () -> si (last l5) ^ il (butlast l5));;
tr "assoc" (fun () -> assoc 2 [1,"a";2,"b";2,"c"]);;
tr "assoc_bad" (fun () -> assoc 9 [1,"a"]);;
tr "rev_assoc" (fun () -> si (rev_assoc "b" [1,"a";2,"b"]));;
tr "index" (fun () -> si (index "c" ["a";"b";"c"]));;
tr "index_bad" (fun () -> si (index "z" ["a"]));;
tr "remove" (fun () -> let x,r = remove (fun x -> x = 4) l5 in si x ^ il r);;
tr "tryfind" (fun () -> si (tryfind (fun x -> note (si x); if x < 4 then failwith "s" else x) l5));;
tr "find_bad" (fun () -> si (find (fun x -> x > 9) l5));;
tr "zip_bad" (fun () -> si (length (zip [1] [1;2])));;
tr "shareout" (fun () -> String.concat "|" (map il (shareout [[0;0];[];[0]] [1;2;3])));;
tr "explode" (fun () -> sl (explode "a b") ^ implode ["x";"y"]);;
tr "gcd" (fun () -> il [gcd 12 18; gcd (-12) 18; gcd 0 0; gcd 7 0]);;
tr "repeat" (fun () -> si (repeat (fun x -> if x > 10 then failwith "s" else x * 2) 1));;
tr "funpow" (fun () -> si (funpow 3 (fun x -> x * 3) 1));;
tr "increasing" (fun () -> string_of_bool (increasing (fun x -> note (si x); -x) 1 2));;
(* Patricia trees. *)
let showf f = "[" ^ String.concat ";" (rev (foldl (fun a x y -> (x ^ "=" ^ si y)::a) [] f)) ^ "]";;
let f1 = itlist (fun (x,y) f -> (x |-> y) f) ["apple",1;"b",2;"c",3;"dd",4;"e",5;"apple",6;"zz",7] undefined;;
tr "func_foldl" (fun () -> showf f1);;
tr "func_foldr" (fun () -> String.concat ";" (foldr (fun x y a -> (x ^ si y)::a) f1 []));;
tr "func_graph" (fun () -> String.concat ";" (map (fun (x,y) -> x ^ si y) (graph f1)));;
tr "func_dom" (fun () -> sl (dom f1));;
tr "func_ran" (fun () -> il (ran f1));;
tr "func_choose" (fun () -> let x,y = choose f1 in x ^ si y);;
tr "func_apply" (fun () -> si (apply f1 "dd") ^ si (tryapplyd f1 "nope" 0));;
tr "func_apply_bad" (fun () -> si (apply f1 "nope"));;
tr "func_defined" (fun () -> string_of_bool (defined f1 "e") ^ string_of_bool (defined f1 "q"));;
tr "func_undefine" (fun () -> showf (undefine "c" (undefine "zz" f1)));;
let f2 = itlist (fun (x,y) f -> (x |-> y) f) ["b",10;"q",20;"e",-5;"r",1] undefined;;
tr "func_combine" (fun () -> showf (combine (fun x y -> note (si x ^ "+" ^ si y); x + y) (fun x -> x = 0) f1 f2));;
tr "func_mapf" (fun () -> showf (mapf (fun x -> note (si x); x * 10) f1));;
let f3 = itlist (fun i f -> (i |-> i * i) f) (1--40) undefined;;
tr "func_int_foldl" (fun () -> il (foldl (fun a x y -> x::a) [] f3));;
tr "func_choose_int" (fun () -> let x,_ = choose f3 in si x);;
let x = mk_var("x",aty) and y = mk_var("y",aty) and z = mk_var("z",bool_ty);;
let f4 = itlist (fun (k,v) f -> (k |-> v) f) [x,1;y,2;z,3;mk_var("w",aty),4] undefined;;
tr "func_term_foldl" (fun () -> String.concat ";" (foldl (fun a k v -> (fst(dest_var k) ^ si v)::a) [] f4));;
tr "single" (fun () -> showf ("k" |=> 9));;
tr "choose_bad" (fun () -> let x,_ = choose (undefined : (string,int)func) in x);;
