(* Load-fidelity test for Library/bitsize.ml (translated by tools/translator). Keep
   in sync with library/bitsize/bitsize_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
start_trace ();;
#use "Library/bitsize.ml";;
show_trace "Library/bitsize";;
(* BEGIN generated theorem list *)
attempt "bitsize" (fun () -> sthm bitsize);;
attempt "BITSIZE_0" (fun () -> sthm BITSIZE_0);;
attempt "BITSIZE_POW2" (fun () -> sthm BITSIZE_POW2);;
attempt "BITSIZE_1" (fun () -> sthm BITSIZE_1);;
attempt "BITSIZE_2" (fun () -> sthm BITSIZE_2);;
attempt "BITSIZE_LE" (fun () -> sthm BITSIZE_LE);;
attempt "BITSIZE" (fun () -> sthm BITSIZE);;
attempt "BITSIZE_UNIQUE" (fun () -> sthm BITSIZE_UNIQUE);;
attempt "BITSIZE_UNIQUE_ALT" (fun () -> sthm BITSIZE_UNIQUE_ALT);;
attempt "BITSIZE_EQ_0" (fun () -> sthm BITSIZE_EQ_0);;
attempt "BITSIZE_MONO" (fun () -> sthm BITSIZE_MONO);;
attempt "BITSIZE_MAX" (fun () -> sthm BITSIZE_MAX);;
attempt "BITSIZE_MIN" (fun () -> sthm BITSIZE_MIN);;
attempt "BITSIZE_MULT_LE" (fun () -> sthm BITSIZE_MULT_LE);;
attempt "BITSIZE_REV_EQ" (fun () -> sthm BITSIZE_REV_EQ);;
attempt "BITSIZE_REV" (fun () -> sthm BITSIZE_REV);;
attempt "BITSIZE_REV_EQ_ALT" (fun () -> sthm BITSIZE_REV_EQ_ALT);;
attempt "BITSIZE_REV_ALT" (fun () -> sthm BITSIZE_REV_ALT);;
attempt "LE_BITSIZE" (fun () -> sthm LE_BITSIZE);;
attempt "LE_BITSIZE_ALT" (fun () -> sthm LE_BITSIZE_ALT);;
attempt "BITSIZE_UNIQUE_EQ" (fun () -> sthm BITSIZE_UNIQUE_EQ);;
attempt "BITSIZE_MULT" (fun () -> sthm BITSIZE_MULT);;
attempt "BITSIZE_MULT_ADD" (fun () -> sthm BITSIZE_MULT_ADD);;
attempt "BITSIZE_DIV" (fun () -> sthm BITSIZE_DIV);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
