(* Load-fidelity test for Library/rabin_test.ml (translated by tools/translator). Keep
   in sync with library/rabin_test/rabin_test_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "Library/wo.ml";;
#use "Library/card.ml";;
#use "Library/matroids.ml";;
#use "Library/binomial.ml";;
#use "Library/iter.ml";;
#use "Library/prime.ml";;
#use "Library/pocklington.ml";;
#use "Library/ringtheory.ml";;
#use "Library/fieldtheory.ml";;
start_trace ();;
#use "Library/rabin_test.ml";;
show_trace "Library/rabin_test";;
(* BEGIN generated theorem list *)
attempt "RING_DIVIDES_POW_ITERATE" (fun () -> sthm RING_DIVIDES_POW_ITERATE);;
attempt "POLY_NONUNIT_DEGREE_GE_1" (fun () -> sthm POLY_NONUNIT_DEGREE_GE_1);;
attempt "RING_DIVIDES_REDUCE" (fun () -> sthm RING_DIVIDES_REDUCE);;
attempt "FIELD_NONZERO_PRODUCT_PERMUTE" (fun () -> sthm FIELD_NONZERO_PRODUCT_PERMUTE);;
attempt "FINITE_FIELD_ELEMENT_POW" (fun () -> sthm FINITE_FIELD_ELEMENT_POW);;
attempt "QUOTIENT_POLY_RING_FINITE_CARD" (fun () -> sthm QUOTIENT_POLY_RING_FINITE_CARD);;
attempt "IRREDUCIBLE_DIVIDES_XQ_MINUS_X_GEN" (fun () -> sthm IRREDUCIBLE_DIVIDES_XQ_MINUS_X_GEN);;
attempt "IRREDUCIBLE_DIVIDES_XQ_MINUS_X" (fun () -> sthm IRREDUCIBLE_DIVIDES_XQ_MINUS_X);;
attempt "FINITE_FIELD_POW_ITERATE" (fun () -> sthm FINITE_FIELD_POW_ITERATE);;
attempt "RING_ENDOMORPHISM_FROBENIUS_ITERATE" (fun () -> sthm RING_ENDOMORPHISM_FROBENIUS_ITERATE);;
attempt "FIELD_ROOTS_BOUND" (fun () -> sthm FIELD_ROOTS_BOUND);;
attempt "FINITE_FIELD_CARD_CHAR_POWER" (fun () -> sthm FINITE_FIELD_CARD_CHAR_POWER);;
attempt "IRREDUCIBLE_DIVIDES_DEGREE_BOUND" (fun () -> sthm IRREDUCIBLE_DIVIDES_DEGREE_BOUND);;
attempt "IRREDUCIBLE_DIVIDES_DEGREE" (fun () -> sthm IRREDUCIBLE_DIVIDES_DEGREE);;
attempt "RABIN_IRREDUCIBILITY_NECESSARY" (fun () -> sthm RABIN_IRREDUCIBILITY_NECESSARY);;
attempt "RABIN_IRREDUCIBILITY_SUFFICIENT" (fun () -> sthm RABIN_IRREDUCIBILITY_SUFFICIENT);;
attempt "RABIN_IRREDUCIBILITY_TEST" (fun () -> sthm RABIN_IRREDUCIBILITY_TEST);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
