(* Load-fidelity test for Library/iter.ml (translated by tools/translator). Keep
   in sync with library/iter/iter_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
start_trace ();;
#use "Library/iter.ml";;
show_trace "Library/iter";;
(* BEGIN generated theorem list *)
attempt "ITER" (fun () -> sthm ITER);;
attempt "ITER_POINTLESS" (fun () -> sthm ITER_POINTLESS);;
attempt "ITER_ALT" (fun () -> sthm ITER_ALT);;
attempt "ITER_ALT_POINTLESS" (fun () -> sthm ITER_ALT_POINTLESS);;
attempt "ITER_1" (fun () -> sthm ITER_1);;
attempt "ITER_ADD" (fun () -> sthm ITER_ADD);;
attempt "ITER_ADD_POINTLESS" (fun () -> sthm ITER_ADD_POINTLESS);;
attempt "ITER_MUL" (fun () -> sthm ITER_MUL);;
attempt "ITER_FIXPOINT" (fun () -> sthm ITER_FIXPOINT);;
attempt "ORDER_EXISTENCE_GEN" (fun () -> sthm ORDER_EXISTENCE_GEN);;
attempt "ORDER_EXISTENCE_ITER" (fun () -> sthm ORDER_EXISTENCE_ITER);;
attempt "ORDER_EXISTENCE_CARD" (fun () -> sthm ORDER_EXISTENCE_CARD);;
attempt "ORDER_EXISTENCE_FINITE" (fun () -> sthm ORDER_EXISTENCE_FINITE);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
