(* Load-fidelity test for Library/binary.ml (translated by tools/translator). Keep
   in sync with library/binary/binary_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
start_trace ();;
#use "Library/binary.ml";;
show_trace "Library/binary";;
(* BEGIN generated theorem list *)
attempt "BOUNDED_FINITE" (fun () -> sthm BOUNDED_FINITE);;
attempt "EVEN_NSUM" (fun () -> sthm EVEN_NSUM);;
attempt "bitset" (fun () -> sthm bitset);;
attempt "binarysum" (fun () -> sthm binarysum);;
attempt "BITSET_BOUND_LEMMA" (fun () -> sthm BITSET_BOUND_LEMMA);;
attempt "BITSET_BOUND_WEAK" (fun () -> sthm BITSET_BOUND_WEAK);;
attempt "FINITE_BITSET" (fun () -> sthm FINITE_BITSET);;
attempt "BITSET_0" (fun () -> sthm BITSET_0);;
attempt "BITSET_STEP" (fun () -> sthm BITSET_STEP);;
attempt "BINARYSUM_BITSET" (fun () -> sthm BINARYSUM_BITSET);;
attempt "BITSET_EQ" (fun () -> sthm BITSET_EQ);;
attempt "BITSET_EQ_EMPTY" (fun () -> sthm BITSET_EQ_EMPTY);;
attempt "BINARYSUM_BOUND_LEMMA" (fun () -> sthm BINARYSUM_BOUND_LEMMA);;
attempt "BINARYSUM_DIV_DIVISIBLE" (fun () -> sthm BINARYSUM_DIV_DIVISIBLE);;
attempt "BINARYSUM_DIV" (fun () -> sthm BINARYSUM_DIV);;
attempt "BITSET_BINARYSUM" (fun () -> sthm BITSET_BINARYSUM);;
attempt "BINARYSUM_BOUND" (fun () -> sthm BINARYSUM_BOUND);;
attempt "BITSET_BOUND" (fun () -> sthm BITSET_BOUND);;
attempt "BITSET_BOUND_EQ" (fun () -> sthm BITSET_BOUND_EQ);;
attempt "BINARYSUM_BOUND_EQ" (fun () -> sthm BINARYSUM_BOUND_EQ);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
