(* Load-fidelity test for Library/word_automata.ml (translated by tools/translator). Keep
   in sync with library/word_automata/word_automata_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "Library/rstc.ml";;
#use "Library/bdd.ml";;
#use "Library/words.ml";;
start_trace ();;
#use "Library/word_automata.ml";;
show_trace "Library/word_automata";;
(* BEGIN generated theorem list *)
attempt "OVERAPPROXIMATE_REACHABLE" (fun () -> sthm OVERAPPROXIMATE_REACHABLE);;
attempt "word_shladd" (fun () -> sthm word_shladd);;
attempt "WORD_SHLADD" (fun () -> sthm WORD_SHLADD);;
attempt "BIT_WORD_SHLADD" (fun () -> sthm BIT_WORD_SHLADD);;
attempt "WORD_SHLADD_0" (fun () -> sthm WORD_SHLADD_0);;
attempt "WORD_NUMERAL_SHLADD" (fun () -> sthm WORD_NUMERAL_SHLADD);;
attempt "WORD_USHR_SHLADD" (fun () -> sthm WORD_USHR_SHLADD);;
attempt "WORD_ISHR_SHLADD" (fun () -> sthm WORD_ISHR_SHLADD);;
attempt "DEFINE_WORD_INT_MIN" (fun () -> sthm DEFINE_WORD_INT_MIN);;
attempt "VAL_LT_ELIM_THM" (fun () -> sthm VAL_LT_ELIM_THM);;
attempt "IVAL_LT_ELIM_THM" (fun () -> sthm IVAL_LT_ELIM_THM);;
attempt "IVAL_LT_0_ELIM_THM" (fun () -> sthm IVAL_LT_0_ELIM_THM);;
attempt "CONJ_WORD_EQ_0" (fun () -> sthm CONJ_WORD_EQ_0);;
attempt "DISJ_WORD_EQ_0" (fun () -> sthm DISJ_WORD_EQ_0);;
attempt "LSB_CARRYING" (fun () -> sthm LSB_CARRYING);;
attempt "XSB_CARRYING" (fun () -> sthm XSB_CARRYING);;
attempt "WORD_MUL_SHLADD" (fun () -> sthm WORD_MUL_SHLADD);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
