(* Load-fidelity test for LP_arith/lp_tests.ml (translated by tools/translator). Keep
   in sync with lp_arith/lp_tests/lp_tests_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "LP_arith/lp_arith.ml";;
start_trace ();;
#use "LP_arith/lp_tests.ml";;
show_trace "LP_arith/lp_tests";;
(* BEGIN generated theorem list *)
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* LP_arith/make.ml's two runs of LP_ARITH (cdd_cert runs recorded and replayed) *)
attempt "LP_ARITH rec_seq" (fun () -> sthm (LP_ARITH rec_seq));;
attempt "LP_ARITH test_std" (fun () -> sthm (LP_ARITH test_std));;
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
