(* Load-fidelity test for Minisat/minisat_prove.ml (translated by tools/translator). Keep
   in sync with minisat/minisat_prove/minisat_prove_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "Minisat/sat_common_tools.ml";;
#use "Minisat/dimacs_tools.ml";;
#use "Minisat/sat_solvers.ml";;
#use "Minisat/sat_script.ml";;
#use "Minisat/sat_tools.ml";;
#use "Minisat/minisat_parse.ml";;
#use "Minisat/minisat_resolve.ml";;
start_trace ();;
#use "Minisat/minisat_prove.ml";;
show_trace "Minisat/minisat_prove";;
(* BEGIN generated theorem list *)
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* SAT_PROVE runs MiniSat (the directory's own test.ml also needs zChaff):
   three small problems, the runs recorded and replayed *)
attempt "SAT_PROVE 1" (fun () -> sthm (SAT_PROVE (tm "(p ==> q) <=> (p <=> p /\\ q)")));;
attempt "SAT_PROVE 2" (fun () -> sthm (SAT_PROVE (tm "((p ==> q) ==> p) ==> p")));;
attempt "SAT_PROVE 3" (fun () -> sthm (SAT_PROVE (tm "(a \\/ b) /\\ (~a \\/ c) /\\ (~b \\/ c) ==> c")));;
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
