(* Load-fidelity test for Minisat/sat_script.ml (translated by tools/translator). Keep
   in sync with minisat/sat_script/sat_script_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "Minisat/sat_common_tools.ml";;
#use "Minisat/dimacs_tools.ml";;
#use "Minisat/sat_solvers.ml";;
start_trace ();;
#use "Minisat/sat_script.ml";;
show_trace "Minisat/sat_script";;
(* BEGIN generated theorem list *)
attempt "AND_IMP" (fun () -> sthm AND_IMP);;
attempt "AND_IMP2" (fun () -> sthm AND_IMP2);;
attempt "AND_IMP3" (fun () -> sthm AND_IMP3);;
attempt "NOT_NOT" (fun () -> sthm NOT_NOT);;
attempt "AND_INV" (fun () -> sthm AND_INV);;
attempt "AND_INV_IMP" (fun () -> sthm AND_INV_IMP);;
attempt "OR_DUAL" (fun () -> sthm OR_DUAL);;
attempt "OR_DUAL2" (fun () -> sthm OR_DUAL2);;
attempt "OR_DUAL3" (fun () -> sthm OR_DUAL3);;
attempt "AND_INV2" (fun () -> sthm AND_INV2);;
attempt "NOT_ELIM2" (fun () -> sthm NOT_ELIM2);;
attempt "IMP_F_EQ_F" (fun () -> sthm IMP_F_EQ_F);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
