(* Load-fidelity test for miz3/Samples/forster.ml (translated by tools/translator). Keep
   in sync with miz3/Samples/forster/forster_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "Examples/holby.ml";;
#use "miz3/miz3.ml";;
start_trace ();;
#use "miz3/Samples/forster.ml";;
show_trace "miz3/Samples/forster";;
(* BEGIN generated theorem list *)
attempt "FORSTER_PUZZLE_1" (fun () -> sthm FORSTER_PUZZLE_1);;
attempt "FORSTER_PUZZLE_2" (fun () -> sthm FORSTER_PUZZLE_2);;
attempt "FORSTER_PUZZLE_3" (fun () -> sthm FORSTER_PUZZLE_3);;
attempt "FORSTER_PUZZLE_4" (fun () -> sthm FORSTER_PUZZLE_4);;
attempt "num_MONO_LT_SUC" (fun () -> sthm num_MONO_LT_SUC);;
attempt "FORSTER_PUZZLE_5" (fun () -> sthm FORSTER_PUZZLE_5);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
