(* Load-fidelity test for miz3/Samples/irrat2.ml (translated by tools/translator). Keep
   in sync with miz3/Samples/irrat2/irrat2_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "Examples/holby.ml";;
#use "miz3/miz3.ml";;
#use "Library/analysis.ml";;
#use "Library/transc.ml";;
#use "Examples/sos.ml";;
start_trace ();;
#use "miz3/Samples/irrat2.ml";;
show_trace "miz3/Samples/irrat2";;
(* BEGIN generated theorem list *)
attempt "rational" (fun () -> sthm rational);;
attempt "NSQRT_2_1" (fun () -> sthm NSQRT_2_1);;
attempt "SQRT_2_IRRATIONAL_1" (fun () -> sthm SQRT_2_IRRATIONAL_1);;
attempt "NSQRT_2_2" (fun () -> sthm NSQRT_2_2);;
attempt "SQRT_2_IRRATIONAL_2" (fun () -> sthm SQRT_2_IRRATIONAL_2);;
attempt "NSQRT_2_3" (fun () -> sthm NSQRT_2_3);;
attempt "SQRT_2_IRRATIONAL_3" (fun () -> sthm SQRT_2_IRRATIONAL_3);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
