(* Load-fidelity test for Mizarlight/duality.ml (translated by tools/translator). Keep
   in sync with mizarlight/duality/duality_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "Mizarlight/make.ml";;
#use "Mizarlight/miz2a.ml";;
start_trace ();;
#use "Mizarlight/duality.ml";;
show_trace "Mizarlight/duality";;
(* BEGIN generated theorem list *)
attempt "projective" (fun () -> sthm projective);;
attempt "LEMMA_1" (fun () -> sthm LEMMA_1);;
attempt "LEMMA_2" (fun () -> sthm LEMMA_2);;
attempt "PROJECTIVE_DUALITY" (fun () -> sthm PROJECTIVE_DUALITY);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
attempt "axioms" (fun () -> String.concat "\n" (List.map sthm (axioms())));;
