(* Load-fidelity test for normalizer.ml (translated by tools/translator). Keep
   in sync with normalizer/normalizer_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
start_trace ();;
#use "normalizer.ml";;
show_trace "normalizer";;
(* BEGIN generated theorem list *)
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (length (definitions())));;
(* BEGIN EXTRA *)
attempt "norm_sq" (fun () -> sthm (NUM_NORMALIZE_CONV (tm "(x + 1) * (x + 2)")));;
attempt "norm_cube" (fun () -> sthm (NUM_NORMALIZE_CONV (tm "(a + b) EXP 3")));;
attempt "norm_cancel" (fun () -> sthm (NUM_NORMALIZE_CONV (tm "x * y + y * x + 0 * z")));;
attempt "norm_const" (fun () -> sthm (NUM_NORMALIZE_CONV (tm "2 * 3 + 4")));;
attempt "norm_poly" (fun () -> sthm (NUM_NORMALIZE_CONV (tm "(x + y) * (x + y) - x * x")));;
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
