(* Load-fidelity test for Ntrie/ntrie.ml (translated by tools/translator). Keep
   in sync with ntrie/ntrie/ntrie_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
start_trace ();;
#use "Ntrie/ntrie.ml";;
show_trace "Ntrie/ntrie";;
(* BEGIN generated theorem list *)
attempt "NTRIE" (fun () -> sthm NTRIE);;
attempt "NEMPTY" (fun () -> sthm NEMPTY);;
attempt "NZERO" (fun () -> sthm NZERO);;
attempt "NNODE" (fun () -> sthm NNODE);;
attempt "NTRIE_RELATIONS" (fun () -> sthm NTRIE_RELATIONS);;
attempt "NTRIE_IN" (fun () -> sthm NTRIE_IN);;
attempt "NTRIE_SUBSET" (fun () -> sthm NTRIE_SUBSET);;
attempt "NTRIE_EQ" (fun () -> sthm NTRIE_EQ);;
attempt "NTRIE_SING" (fun () -> sthm NTRIE_SING);;
attempt "NTRIE_INSERT" (fun () -> sthm NTRIE_INSERT);;
attempt "NTRIE_UNION" (fun () -> sthm NTRIE_UNION);;
attempt "NTRIE_INTER" (fun () -> sthm NTRIE_INTER);;
attempt "NTRIE_DELETE" (fun () -> sthm NTRIE_DELETE);;
attempt "NTRIE_DISJOINT" (fun () -> sthm NTRIE_DISJOINT);;
attempt "NTRIE_DIFF" (fun () -> sthm NTRIE_DIFF);;
attempt "NTRIE_IMAGE_DEF" (fun () -> sthm NTRIE_IMAGE_DEF);;
attempt "NTRIE_IMAGE" (fun () -> sthm NTRIE_IMAGE);;
attempt "IMAGE_EQ_NTRIE_IMAGE" (fun () -> sthm IMAGE_EQ_NTRIE_IMAGE);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
