(* Load-fidelity and behaviour test for nums.ml (translated by
   tools/translator). Keep in sync with nums/nums_ref_test.mbt (the theorem
   list part is generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
start_trace ();;
#use "nums.ml";;
show_trace "nums";;
(* BEGIN generated theorem list *)
attempt "ONE_ONE" (fun () -> sthm ONE_ONE);;
attempt "ONTO" (fun () -> sthm ONTO);;
attempt "INFINITY_AX" (fun () -> sthm INFINITY_AX);;
attempt "IND_SUC_0_EXISTS" (fun () -> sthm IND_SUC_0_EXISTS);;
attempt "IND_SUC_SPEC" (fun () -> sthm IND_SUC_SPEC);;
attempt "IND_SUC_INJ" (fun () -> sthm IND_SUC_INJ);;
attempt "IND_SUC_0" (fun () -> sthm IND_SUC_0);;
attempt "NUM_REP_RULES" (fun () -> sthm NUM_REP_RULES);;
attempt "NUM_REP_INDUCT" (fun () -> sthm NUM_REP_INDUCT);;
attempt "NUM_REP_CASES" (fun () -> sthm NUM_REP_CASES);;
attempt "ZERO_DEF" (fun () -> sthm ZERO_DEF);;
attempt "SUC_DEF" (fun () -> sthm SUC_DEF);;
attempt "SUC_INJ" (fun () -> sthm SUC_INJ);;
attempt "NUMERAL" (fun () -> sthm NUMERAL);;
attempt "NOT_SUC" (fun () -> sthm NOT_SUC);;
attempt "num_INDUCTION" (fun () -> sthm num_INDUCTION);;
attempt "num_Axiom" (fun () -> sthm num_Axiom);;
attempt "num_RECURSION" (fun () -> sthm num_RECURSION);;
attempt "num_CASES" (fun () -> sthm num_CASES);;
attempt "BIT0_DEF" (fun () -> sthm BIT0_DEF);;
attempt "BIT1_DEF" (fun () -> sthm BIT1_DEF);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (length (definitions())));;
attempt "mk_numeral" (fun () -> stm (mk_numeral (num 12345)));;
attempt "mk_big" (fun () -> string_of_term (mk_numeral (power_num (num 2) (num 70))));;
attempt "dest" (fun () -> string_of_num (dest_numeral (tm "123456789")));;
attempt "small" (fun () -> string_of_int (dest_small_numeral (mk_small_numeral 42)));;
attempt "is_numeral" (fun () -> string_of_bool (is_numeral (tm "7")) ^ " " ^ string_of_bool (is_numeral (tm "x:num")));;
attempt "print" (fun () -> string_of_term (tm "SUC 0 = 1"));;
attempt "neg" (fun () -> stm (mk_numeral (num (-1))));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
