(* Load-fidelity test for Permutation/qsort.ml (translated by tools/translator). Keep
   in sync with permutation/qsort/qsort_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "Permutation/morelist.ml";;
#use "Permutation/permuted.ml";;
#use "Permutation/permutation.ml";;
start_trace ();;
#use "Permutation/qsort.ml";;
show_trace "Permutation/qsort";;
(* BEGIN generated theorem list *)
attempt "ORDERED_RULES" (fun () -> sthm ORDERED_RULES);;
attempt "ORDERED_INDUCT" (fun () -> sthm ORDERED_INDUCT);;
attempt "ORDERED_CASES" (fun () -> sthm ORDERED_CASES);;
attempt "ORDERED_CONS" (fun () -> sthm ORDERED_CONS);;
attempt "ORDERED_APPEND" (fun () -> sthm ORDERED_APPEND);;
attempt "ORDERED_PAIRWISE" (fun () -> sthm ORDERED_PAIRWISE);;
attempt "QSORT" (fun () -> sthm QSORT);;
attempt "COUNT_QSORT" (fun () -> sthm COUNT_QSORT);;
attempt "QSORT_PERMUTED" (fun () -> sthm QSORT_PERMUTED);;
attempt "ALL_QSORT" (fun () -> sthm ALL_QSORT);;
attempt "LENGTH_QSORT" (fun () -> sthm LENGTH_QSORT);;
attempt "MEM_QSORT" (fun () -> sthm MEM_QSORT);;
attempt "ORDERED_QSORT" (fun () -> sthm ORDERED_QSORT);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
