(* Load-fidelity test for Permutation/nummax.ml (translated by tools/translator). Keep
   in sync with permutation/nummax/nummax_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "Permutation/morelist.ml";;
start_trace ();;
#use "Permutation/nummax.ml";;
show_trace "Permutation/nummax";;
(* BEGIN generated theorem list *)
attempt "MAX_LT" (fun () -> sthm MAX_LT);;
attempt "MAX_LE" (fun () -> sthm MAX_LE);;
attempt "LT_MAX" (fun () -> sthm LT_MAX);;
attempt "LE_MAX" (fun () -> sthm LE_MAX);;
attempt "MAX_SYM" (fun () -> sthm MAX_SYM);;
attempt "MAX_ASSOC" (fun () -> sthm MAX_ASSOC);;
attempt "MAX_ACI" (fun () -> sthm MAX_ACI);;
attempt "MAX_0" (fun () -> sthm MAX_0);;
attempt "MAXL" (fun () -> sthm MAXL);;
attempt "MAXL_LE" (fun () -> sthm MAXL_LE);;
attempt "LT_MAXL" (fun () -> sthm LT_MAXL);;
attempt "LE_MAXL" (fun () -> sthm LE_MAXL);;
attempt "MEM_MAXL" (fun () -> sthm MEM_MAXL);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
