(* Hand-built printer checks (before the parser exists). Keep in sync with
   printer/printer_ref_test.mbt. *)
let a = mk_vartype "A" and b = mk_vartype "B";;
let fn x y = mk_fun_ty x y;;
let bb = fn bool_ty (fn bool_ty bool_ty);;
let _ = new_type("num",0) and _ = new_type("prod",2) and _ = new_type("sum",2)
  and _ = new_type("cart",2) and _ = new_type("list",1) and _ = new_type("char",0);;
let _ = new_type("1",0) and _ = new_type("tybit0",1) and _ = new_type("tybit1",1);;
let num_ty = mk_type("num",[]);;
let prod x y = mk_type("prod",[x;y]) and sum x y = mk_type("sum",[x;y]);;
let cart x y = mk_type("cart",[x;y]) and lst x = mk_type("list",[x]);;
let char_ty = mk_type("char",[]);;
let p t = out (string_of_type t);;
p (fn a (fn b a));; p (fn (fn a b) a);; p (prod a (prod b a));; p (prod (prod a b) a);;
p (sum a (prod b num_ty));; p (fn (sum a b) (prod a b));; p (cart num_ty (mk_finty (num 3)));;
p (lst (lst a));; p (mk_type("prod",[fn a b; lst num_ty]));; p (mk_finty (num 12));;
p (cart (cart a b) num_ty);; p (cart a (cart b num_ty));; p (mk_vartype "?123");;
let _ = map new_constant
  ["/\\",bb; "\\/",bb; "==>",bb; "~",fn bool_ty bool_ty; "T",bool_ty; "F",bool_ty;
   "!",fn (fn a bool_ty) bool_ty; "?",fn (fn a bool_ty) bool_ty;
   "NUMERAL",fn num_ty num_ty; "BIT0",fn num_ty num_ty; "BIT1",fn num_ty num_ty;
   "_0",num_ty; "+",fn num_ty (fn num_ty num_ty); "*",fn num_ty (fn num_ty num_ty);
   "-",fn num_ty (fn num_ty num_ty); "SUC",fn num_ty num_ty;
   "COND",fn bool_ty (fn a (fn a a)); "INSERT",fn a (fn (fn a bool_ty) (fn a bool_ty));
   "EMPTY",fn a bool_ty; "UNIV",fn a bool_ty; ",",fn a (fn b (prod a b));
   "CONS",fn a (fn (lst a) (lst a)); "NIL",lst a; "ASCII",
   itlist fn [bool_ty;bool_ty;bool_ty;bool_ty;bool_ty;bool_ty;bool_ty;bool_ty] char_ty;
   "DECIMAL",fn num_ty (fn num_ty num_ty); "GSPEC",fn (fn a bool_ty) (fn a bool_ty);
   "SETSPEC",fn a (fn bool_ty (fn a bool_ty)); "GEQ",fn a (fn a bool_ty);
   "GABS",fn (fn a bool_ty) a; "LET",fn (fn a b) (fn a b); "LET_END",fn a a];;
parse_as_infix("==>",(4,"right"));; parse_as_infix("\\/",(16,"right"));;
parse_as_infix("/\\",(20,"right"));; parse_as_infix("=",(12,"right"));;
parse_as_infix("+",(16,"right"));; parse_as_infix("*",(20,"right"));;
parse_as_infix("-",(18,"left"));; parse_as_infix(",",(14,"right"));;
parse_as_binder "!";; parse_as_binder "?";; parse_as_binder "\\";; parse_as_prefix "~";;
attempt "infixes" (fun () -> String.concat " " (map (fun (s,(n,d)) -> s ^ "/" ^ string_of_int n ^ d) (infixes())));;
let x = mk_var("x",num_ty) and y = mk_var("y",num_ty) and z = mk_var("z",num_ty);;
let pv = mk_var("p",bool_ty) and q = mk_var("q",bool_ty) and r = mk_var("r",bool_ty);;
let bin s l r = mk_comb(mk_comb(mk_const(s,[]),l),r);;
let ibin s l r = list_mk_icomb s [l;r];;
let neg t = mk_comb(mk_const("~",[]),t);;
let numeral k = let rec bits k = if k = 0 then mk_const("_0",[]) else mk_comb(mk_const((if k mod 2 = 0 then "BIT0" else "BIT1"),[]), bits (k / 2)) in mk_comb(mk_const("NUMERAL",[]), bits k);;
let t s tm = attempt s (fun () -> string_of_term tm);;
t "plus_assoc" (bin "+" x (bin "+" y z));;
t "plus_left" (bin "+" (bin "+" x y) z);;
t "minus_left" (bin "-" (bin "-" x y) z);;
t "minus_right" (bin "-" x (bin "-" y z));;
t "prec" (bin "*" (bin "+" x y) (bin "+" y (bin "*" z x)));;
t "imp_chain" (bin "==>" pv (bin "==>" q (bin "\\/" r (bin "/\\" pv q))));;
t "neg" (neg (neg (bin "/\\" pv q)));;
t "neg_atom" (neg pv);;
t "eq" (mk_eq(bin "+" x y, numeral 42));;
t "forall" (mk_binder "!" (x, mk_binder "!" (y, mk_eq(x,y))));;
t "exists" (mk_binder "?" (pv, bin "\\/" pv (neg pv)));;
t "lambda" (mk_abs(x, mk_abs(y, bin "+" x y)));;
t "app_lambda" (mk_comb(mk_abs(x, bin "+" x x), numeral 3));;
t "suc" (mk_comb(mk_const("SUC",[]), mk_comb(mk_const("SUC",[]), bin "+" x y)));;
t "numerals" (bin "+" (numeral 0) (bin "+" (numeral 1) (numeral 123456789)));;
t "cond" (list_mk_icomb "COND" [pv; x; y]);;
let rec cond_chain n = if n = 0 then x else list_mk_icomb "COND" [mk_var("c" ^ string_of_int n, bool_ty); numeral n; cond_chain (n - 1)];;
t "cond_long" (cond_chain 6);;
t "pair" (ibin "," x (ibin "," y pv));;
let ins e s = ibin "INSERT" e s;;
let empty ty = inst [ty,a] (mk_const("EMPTY",[]));;
t "finite_set" (ins x (ins y (ins (numeral 2) (empty num_ty))));;
t "empty" (empty num_ty);;
t "univ" (inst [num_ty,a] (mk_const("UNIV",[])));;
let cons h l = ibin "CONS" h l;;
let nil ty = inst [ty,a] (mk_const("NIL",[]));;
t "list" (cons x (cons y (nil num_ty)));;
let tf bit = mk_const((if bit then "T" else "F"),[]);;
let chr c = let k = Char.code c in list_mk_comb(mk_const("ASCII",[]), map (fun i -> tf ((k lsr (7 - i)) land 1 = 1)) (0--7));;
let str s = itlist (fun c l -> cons (chr c) l) (explode s |> map (fun s -> s.[0])) (nil char_ty);;
t "string" (str "hi \"there\"\n\t\\");;
t "string_empty_is_list" (nil char_ty);;
t "decimal" (bin "DECIMAL" (numeral 12345) (numeral 100));;
t "decimal_int" (bin "DECIMAL" (numeral 7) (numeral 1));;
t "decimal_bad" (bin "DECIMAL" (numeral 7) (numeral 3));;
let gx = mk_var("GEN%PVAR%0", num_ty);;
let comp = mk_comb(inst [num_ty,a] (mk_const("GSPEC",[])), mk_abs(gx, mk_binder "?" (x, list_mk_icomb "SETSPEC" [gx; bin "==>" pv (mk_eq(x,y)); bin "+" x (numeral 1)])));;
t "comprehension" comp;;
t "gabs" (mk_gabs(ibin "," x y, bin "+" x y));;
t "let" (mk_let([x, numeral 1; y, bin "+" x x], bin "*" x y));;
let rec big n = if n = 0 then x else bin "+" (bin "*" (mk_var("long_variable_name_" ^ string_of_int n, num_ty)) y) (big (n - 1));;
t "wrap" (big 12);;
t "wrap_imp" (itlist (fun i acc -> bin "==>" (mk_eq(mk_var("hypothesis_" ^ string_of_int i, num_ty), numeral i)) acc) (1--8) pv);;
let itv = mk_var("v", mk_vartype "?7");;
t "invented" (mk_eq(itv, itv));;
print_types_of_subterms := 2;;
t "types_all" (bin "+" x (numeral 1));;
print_types_of_subterms := 1;;
t "infix_atom" (mk_const("+",[]));;
t "binder_atom" (mk_comb(mk_const("!",[a,a]) |> inst [num_ty,a], mk_var("P", fn num_ty bool_ty)));;
the_interface := ["++",("+",fn num_ty (fn num_ty num_ty))];;
parse_as_infix("++",(16,"right"));;
t "interface" (bin "+" x y);;
the_interface := [];;
attempt "thm" (fun () -> string_of_thm (ASSUME (bin "/\\" pv q)));;
attempt "thm2" (fun () -> string_of_thm (DEDUCT_ANTISYM_RULE (ASSUME pv) (ASSUME q)));;
set_margin 30;;
t "wrap_30" (big 5);;
attempt "thm_30" (fun () -> string_of_thm (DEDUCT_ANTISYM_RULE (ASSUME (mk_eq(big 2, x))) (ASSUME q)));;
set_margin 78;;
t "wrap_78_again" (big 5);;
