(* Load-fidelity test for realarith.ml (translated by tools/translator). Keep
   in sync with realarith/realarith_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
start_trace ();;
#use "realarith.ml";;
show_trace "realarith";;
(* BEGIN generated theorem list *)
attempt "REAL_LTE_TOTAL" (fun () -> sthm REAL_LTE_TOTAL);;
attempt "REAL_LET_TOTAL" (fun () -> sthm REAL_LET_TOTAL);;
attempt "REAL_LT_IMP_LE" (fun () -> sthm REAL_LT_IMP_LE);;
attempt "REAL_LTE_TRANS" (fun () -> sthm REAL_LTE_TRANS);;
attempt "REAL_LET_TRANS" (fun () -> sthm REAL_LET_TRANS);;
attempt "REAL_LT_TRANS" (fun () -> sthm REAL_LT_TRANS);;
attempt "REAL_LE_ADD" (fun () -> sthm REAL_LE_ADD);;
attempt "REAL_LTE_ANTISYM" (fun () -> sthm REAL_LTE_ANTISYM);;
attempt "REAL_SUB_LE" (fun () -> sthm REAL_SUB_LE);;
attempt "REAL_NEG_SUB" (fun () -> sthm REAL_NEG_SUB);;
attempt "REAL_LE_LT" (fun () -> sthm REAL_LE_LT);;
attempt "REAL_SUB_LT" (fun () -> sthm REAL_SUB_LT);;
attempt "REAL_NOT_LT" (fun () -> sthm REAL_NOT_LT);;
attempt "REAL_SUB_0" (fun () -> sthm REAL_SUB_0);;
attempt "REAL_LT_LE" (fun () -> sthm REAL_LT_LE);;
attempt "REAL_LT_REFL" (fun () -> sthm REAL_LT_REFL);;
attempt "REAL_LTE_ADD" (fun () -> sthm REAL_LTE_ADD);;
attempt "REAL_LET_ADD" (fun () -> sthm REAL_LET_ADD);;
attempt "REAL_LT_ADD" (fun () -> sthm REAL_LT_ADD);;
attempt "REAL_ENTIRE" (fun () -> sthm REAL_ENTIRE);;
attempt "REAL_LE_NEGTOTAL" (fun () -> sthm REAL_LE_NEGTOTAL);;
attempt "REAL_LE_SQUARE" (fun () -> sthm REAL_LE_SQUARE);;
attempt "REAL_MUL_RID" (fun () -> sthm REAL_MUL_RID);;
attempt "REAL_POW_2" (fun () -> sthm REAL_POW_2);;
attempt "REAL_POLY_CLAUSES" (fun () -> sthm REAL_POLY_CLAUSES);;
attempt "REAL_POLY_NEG_CLAUSES" (fun () -> sthm REAL_POLY_NEG_CLAUSES);;
attempt "REAL_POS" (fun () -> sthm REAL_POS);;
attempt "REAL_LT_NZ" (fun () -> sthm REAL_LT_NZ);;
attempt "REAL_POS_LT" (fun () -> sthm REAL_POS_LT);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
