(* Load-fidelity test for recursion.ml (translated by tools/translator). Keep
   in sync with recursion/recursion_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
start_trace ();;
#use "recursion.ml";;
show_trace "recursion";;
(* BEGIN generated theorem list *)
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (length (definitions())));;
(* BEGIN EXTRA *)
attempt "recdef" (fun () -> sthm (new_recursive_definition num_RECURSION (tm "(dbl 0 = 0) /\\ (!n. dbl (SUC n) = SUC (SUC (dbl n)))")));;
attempt "recdef_fail" (fun () -> sthm (new_recursive_definition num_RECURSION (tm "bad (SUC n) = bad n")));;
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
