(* Load-fidelity test for RichterHilbertAxiomGeometry/UniversalPropCartProd.ml (translated by tools/translator). Keep
   in sync with richterhilbertaxiomgeometry/UniversalPropCartProd/UniversalPropCartProd_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "RichterHilbertAxiomGeometry/readable.ml";;
start_trace ();;
#use "RichterHilbertAxiomGeometry/UniversalPropCartProd.ml";;
show_trace "RichterHilbertAxiomGeometry/UniversalPropCartProd";;
(* BEGIN generated theorem list *)
attempt "NOTIN" (fun () -> sthm NOTIN);;
attempt "CartesianProduct" (fun () -> sthm CartesianProduct);;
attempt "FUNCTION" (fun () -> sthm FUNCTION);;
attempt "SOURCE" (fun () -> sthm SOURCE);;
attempt "FUN" (fun () -> sthm FUN);;
attempt "TARGET" (fun () -> sthm TARGET);;
attempt "FunctionSpace" (fun () -> sthm FunctionSpace);;
attempt "makeFunction" (fun () -> sthm makeFunction);;
attempt "Projection1Function" (fun () -> sthm Projection1Function);;
attempt "Projection2Function" (fun () -> sthm Projection2Function);;
attempt "FunctionComposition" (fun () -> sthm FunctionComposition);;
attempt "IN_CartesianProduct" (fun () -> sthm IN_CartesianProduct);;
attempt "CartesianFstSnd" (fun () -> sthm CartesianFstSnd);;
attempt "FUNCTION_EQ" (fun () -> sthm FUNCTION_EQ);;
attempt "IN_FunctionSpace" (fun () -> sthm IN_FunctionSpace);;
attempt "makeFunction_EQ" (fun () -> sthm makeFunction_EQ);;
attempt "makeFunctionyieldsFUN" (fun () -> sthm makeFunctionyieldsFUN);;
attempt "makeFunctionEq" (fun () -> sthm makeFunctionEq);;
attempt "FunctionSpaceOnSource" (fun () -> sthm FunctionSpaceOnSource);;
attempt "FunctionSpaceOnOffSource" (fun () -> sthm FunctionSpaceOnOffSource);;
attempt "ImpliesTruncatedFunctionSpace" (fun () -> sthm ImpliesTruncatedFunctionSpace);;
attempt "FunFunctionSpaceImplyFunction" (fun () -> sthm FunFunctionSpaceImplyFunction);;
attempt "UseFunctionComposition" (fun () -> sthm UseFunctionComposition);;
attempt "PairProjectionFunctions" (fun () -> sthm PairProjectionFunctions);;
attempt "UniversalPropertyProduct" (fun () -> sthm UniversalPropertyProduct);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
