(* Load-fidelity test for Rqe/condense_thms.ml (translated by tools/translator). Keep
   in sync with rqe/condense_thms/condense_thms_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "Library/analysis.ml";;
#use "Library/poly.ml";;
#use "Rqe/rqe_lib.ml";;
#use "Rqe/rqe_tactics_ext.ml";;
#use "Rqe/util.ml";;
#use "Rqe/rewrites.ml";;
#use "Rqe/basic.ml";;
#use "Rqe/rqe_num.ml";;
#use "Rqe/rqe_real.ml";;
#use "Rqe/list_rewrites.ml";;
#use "Rqe/rqe_list.ml";;
#use "Rqe/timers.ml";;
#use "Rqe/num_calc_simp.ml";;
#use "Rqe/asym.ml";;
#use "Rqe/rol.ml";;
#use "Rqe/poly_ext.ml";;
#use "Rqe/simplify.ml";;
#use "Rqe/lift_qelim.ml";;
#use "Rqe/defs.ml";;
#use "Rqe/testform_thms.ml";;
start_trace ();;
#use "Rqe/condense_thms.ml";;
show_trace "Rqe/condense_thms";;
(* BEGIN generated theorem list *)
attempt "real_cases" (fun () -> sthm real_cases);;
attempt "gt_aux" (fun () -> sthm gt_aux);;
attempt "gen_thm" (fun () -> sthm gen_thm);;
attempt "gen_thm_noleft" (fun () -> sthm gen_thm_noleft);;
attempt "gen_thm_noright" (fun () -> sthm gen_thm_noright);;
attempt "gen_thm_noboth" (fun () -> sthm gen_thm_noboth);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
