(* Load-fidelity test for Rqe/poly_ext.ml (translated by tools/translator). Keep
   in sync with rqe/poly_ext/poly_ext_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "Library/analysis.ml";;
#use "Library/poly.ml";;
#use "Rqe/rqe_lib.ml";;
#use "Rqe/rqe_tactics_ext.ml";;
#use "Rqe/util.ml";;
#use "Rqe/rewrites.ml";;
#use "Rqe/basic.ml";;
#use "Rqe/rqe_num.ml";;
#use "Rqe/rqe_real.ml";;
#use "Rqe/list_rewrites.ml";;
#use "Rqe/rqe_list.ml";;
#use "Rqe/timers.ml";;
#use "Rqe/num_calc_simp.ml";;
#use "Rqe/asym.ml";;
#use "Rqe/rol.ml";;
start_trace ();;
#use "Rqe/poly_ext.ml";;
show_trace "Rqe/poly_ext";;
(* BEGIN generated theorem list *)
attempt "POLY" (fun () -> sthm POLY);;
attempt "POLY_DIFF_CLAUSES" (fun () -> sthm POLY_DIFF_CLAUSES);;
attempt "POLY_DIFF_LEMMA" (fun () -> sthm POLY_DIFF_LEMMA);;
attempt "POLY_DIFF" (fun () -> sthm POLY_DIFF);;
attempt "lt_lem" (fun () -> sthm lt_lem);;
attempt "le_lem" (fun () -> sthm le_lem);;
attempt "eq_lem" (fun () -> sthm eq_lem);;
attempt "POW_PROD_SUM" (fun () -> sthm POW_PROD_SUM);;
attempt "lem1" (fun () -> sthm lem1);;
attempt "lem2" (fun () -> sthm lem2);;
attempt "lem3" (fun () -> sthm lem3);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
