(* Generated by tools/ocaml_ref/str_ref.py: lib/str.mbt against Str. *)
#load "str.cma";;
let count_groups pat =
  let n = ref 1 in
  for i = 0 to String.length pat - 2 do
    if pat.[i] = '\\' && pat.[i + 1] = '(' then incr n
  done;
  !n
let groups n s =
  String.concat ","
    (List.init n (fun i ->
         try "[" ^ String.escaped (Str.matched_group i s) ^ "]"
         with Not_found -> "-" | Invalid_argument _ -> "!"))
let show name f =
  Printf.printf "%s = %s\n" name
    (try f () with
     | Not_found -> "Not_found"
     | Invalid_argument m -> "Invalid_argument " ^ m
     | Failure m -> "Failure " ^ m)
let case pat s =
  Printf.printf "== %s on %s\n" (String.escaped pat) (String.escaped s);
  match (try Some (Str.regexp pat) with Failure m -> Printf.printf "regexp: Failure %s\n" m; None) with
  | None -> ()
  | Some re ->
      let ng = count_groups pat in
      show "match" (fun () ->
          if Str.string_match re s 0 then Printf.sprintf "%d %s" (Str.match_end ()) (groups ng s) else "no");
      show "forward" (fun () ->
          let p = Str.search_forward re s 0 in
          Printf.sprintf "%d-%d %s" p (Str.match_end ()) (groups ng s));
      show "backward" (fun () ->
          let p = Str.search_backward re s (String.length s) in
          Printf.sprintf "%d-%d %s" p (Str.match_end ()) (groups ng s));
      show "replace" (fun () -> String.escaped (Str.global_replace re "<\\0>" s));
      show "replace1" (fun () -> String.escaped (Str.global_replace re "[\\1\\\\\\n]" s));
      show "first" (fun () -> String.escaped (Str.replace_first re "#" s));
      show "split" (fun () -> String.escaped (String.concat "|" (Str.split re s)));;
case "a*" "aaab";;
case "a*" "b";;
case "a+b" "xaab";;
case "a?b" "ab b";;
case "x*" "abc";;
case "" "abc";;
case "[a-c]+" "xxabcabcx";;
case "[^;]*;" "foo; bar; baz";;
case "[]a]+" "a]]b";;
case "[a-]+" "-a-b";;
case "[^]a]+" "xy]a";;
case "[^a-c]" "abcd";;
case "\\(a\\|ab\\)\\(c\\|bcd\\)\\(d*\\)" "abcd";;
case "\\(a*\\)*" "aaa";;
case "\\(a*\\)*" "b";;
case "\\(a*\\)+" "aa";;
case "\\(a*\\)+" "b";;
case "\\(a\\|\\)*" "aa";;
case "\\(a\\|\\)+b" "aab";;
case "\\(a\\|b\\)*c" "ababc";;
case "\\(a+\\)+b" "aaab";;
case "\\(x\\|a*\\)+y" "aaxay";;
case "\\(\\(a\\)\\|\\(b\\)\\)*" "ab";;
case "\\(\\(a\\)\\|\\(b\\)\\)+c" "abac";;
case "\\(.\\)\\1" "abccd";;
case "\\(a*\\)b\\1" "aabaa aba";;
case "\\(a\\)\\|b\\1" "ba";;
case "^b" "a\nb";;
case "b$" "ab\nc";;
case "^$" "a\n\nb";;
case "a^b" "a^b";;
case "a$b" "a$b";;
case "\\$" "a$b";;
case "\\bfoo\\b" "a foo b";;
case "\\bfoo\\b" "afoo foo_ foo";;
case "\\b" "";;
case "o\\b" "foo bar";;
case "a\\|b\\|c" "xcbax";;
case ".*" "ab\ncd";;
case "a.c" "a\nc abc";;
case "\\(.\\|\n\\)*" "ab\ncd";;
case "\\(.\\|\n\\)+d" "ab\ncd e";;
case "\\(foo\\)?bar" "bar foobar";;
case "[ \t\n]+" "a  b\t\nc";;
case "[ \t\n]+" "  a b  ";;
case ",[ ]*" "a, b,c,  d";;
case "," ",a,,b,";;
case "+a" "x+a";;
case "*a" "*a";;
case "a**" "aa";;
case "a+?" "aa";;
case "\\." "a.b";;
case "a\\" "a\\";;
case "\\(" "x";;
case "[abc" "x";;
case "a\\)" "a)";;
case "\\(a" "a";;
case "a\\|" "ba";;
case "\\|a" "ba";;
case "[0-9]+\\(\\.[0-9]+\\)?" "pi 3.14 and 42";;
case "\\([a-z]+\\) \\([a-z]+\\)" "hello world foo";;
case "\\(a\\)\\(b\\)?" "a ab";;
case "\\(a\\|b\\)\\(c\\)?\\1" "aca bb";;
case ";\\|\\[" "a [b]; c";;
case "::[^\n]*" "x ::c\ny :: d";;
case "\\([ \t\n]+proof[ \t\n]+\\|[ \t\n]+qed[ \t\n]*;\\)" " proof\n  intro_TAC H1, H2;\n  A = B [X] by fol H1;\n  fol - H2;\n qed;\n";;
case "[ \t\n]+\\([^][ \t\n]+\\)" "  SUBGOAL_TAC [x]";;
case "[ \t\n]+\\([a-zA-Z0-9_]+\\)" " fol H1 H2";;
case "[ \t\n]+case_split[ \t\n]+\\([^;]+\\)[ \t\n]+by" " case_split a | b by fol;";;
case "[ \t\n]+consider[ \t\n]+\\(\\(.\\|\n\\)+\\)[ \t\n]+such[ \t\n]+that[ \t\n]+\\(\\(.\\|\n\\)+\\)[ \t\n]+\\[\\(\\(.\\|\n\\)*\\)\\][ \t\n]+by" " consider x y such that\n x = y [H] by fol;";;
case "[ \t\n]+proof\\([ \t\n]+\\(.\\|\n\\)*\\)[ \t\n]+qed[ \t\n]*;[ \t\n]*" " proof\n  intro_TAC H1, H2;\n  A = B [X] by fol H1;\n  fol - H2;\n qed;\n  x;\n";;
case "[ \t\n]+\\(assume\\)[ \t\n]+" " assume A [H];";;
case "[ \t\n]*" " \n\t";;
case "[ \t\n]*" " a ";;
