#!/usr/bin/env python3
"""The differential test of lib/str.mbt against OCaml's Str library.

usage: python3 tools/ocaml_ref/str_ref.py

Writes tools/ocaml_ref/str_ref.ml from the cases below, runs it with the
reference toolchain's ocaml (str_ref.expected) and writes
lib/str_ref_test.mbt: the same cases, expecting that output.
"""
import os
import subprocess

REF = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(REF))
WS = "[ \t\n]+"
WS0 = "[ \t\n]*"
PROOF = " proof\n  intro_TAC H1, H2;\n  A = B [X] by fol H1;\n  fol - H2;\n qed;\n"

# (regular expression, subject)
CASES = [
    ("a*", "aaab"), ("a*", "b"), ("a+b", "xaab"), ("a?b", "ab b"), ("x*", "abc"), ("", "abc"),
    ("[a-c]+", "xxabcabcx"), ("[^;]*;", "foo; bar; baz"), ("[]a]+", "a]]b"), ("[a-]+", "-a-b"),
    ("[^]a]+", "xy]a"), ("[^a-c]", "abcd"),
    ("\\(a\\|ab\\)\\(c\\|bcd\\)\\(d*\\)", "abcd"), ("\\(a*\\)*", "aaa"), ("\\(a*\\)*", "b"),
    ("\\(a*\\)+", "aa"), ("\\(a*\\)+", "b"), ("\\(a\\|\\)*", "aa"), ("\\(a\\|\\)+b", "aab"),
    ("\\(a\\|b\\)*c", "ababc"), ("\\(a+\\)+b", "aaab"), ("\\(x\\|a*\\)+y", "aaxay"),
    ("\\(\\(a\\)\\|\\(b\\)\\)*", "ab"), ("\\(\\(a\\)\\|\\(b\\)\\)+c", "abac"),
    ("\\(.\\)\\1", "abccd"), ("\\(a*\\)b\\1", "aabaa aba"), ("\\(a\\)\\|b\\1", "ba"),
    ("^b", "a\nb"), ("b$", "ab\nc"), ("^$", "a\n\nb"), ("a^b", "a^b"), ("a$b", "a$b"), ("\\$", "a$b"),
    ("\\bfoo\\b", "a foo b"), ("\\bfoo\\b", "afoo foo_ foo"), ("\\b", ""), ("o\\b", "foo bar"),
    ("a\\|b\\|c", "xcbax"), (".*", "ab\ncd"), ("a.c", "a\nc abc"), ("\\(.\\|\n\\)*", "ab\ncd"),
    ("\\(.\\|\n\\)+d", "ab\ncd e"), ("\\(foo\\)?bar", "bar foobar"),
    (WS, "a  b\t\nc"), (WS, "  a b  "), (",[ ]*", "a, b,c,  d"), (",", ",a,,b,"),
    ("+a", "x+a"), ("*a", "*a"), ("a**", "aa"), ("a+?", "aa"), ("\\.", "a.b"), ("a\\", "a\\"),
    ("\\(", "x"), ("[abc", "x"), ("a\\)", "a)"), ("\\(a", "a"), ("a\\|", "ba"), ("\\|a", "ba"),
    ("[0-9]+\\(\\.[0-9]+\\)?", "pi 3.14 and 42"), ("\\([a-z]+\\) \\([a-z]+\\)", "hello world foo"),
    ("\\(a\\)\\(b\\)?", "a ab"), ("\\(a\\|b\\)\\(c\\)?\\1", "aca bb"),
    # RichterHilbertAxiomGeometry/readable.ml's
    (";\\|\\[", "a [b]; c"), ("::[^\n]*", "x ::c\ny :: d"),
    ("\\(" + WS + "proof" + WS + "\\|" + WS + "qed" + WS0 + ";" + "\\)", PROOF),
    (WS + "\\([^][ \t\n]+\\)", "  SUBGOAL_TAC [x]"), (WS + "\\([a-zA-Z0-9_]+\\)", " fol H1 H2"),
    (WS + "case_split" + WS + "\\([^;]+\\)" + WS + "by", " case_split a | b by fol;"),
    (WS + "consider" + WS + "\\(\\(.\\|\n\\)+\\)" + WS + "such" + WS + "that" + WS + "\\(\\(.\\|\n\\)+\\)" + WS +
     "\\[\\(\\(.\\|\n\\)*\\)\\]" + WS + "by", " consider x y such that\n x = y [H] by fol;"),
    (WS + "proof\\(" + WS + "\\(.\\|\n\\)*\\)" + WS + "qed" + WS0 + ";" + WS0, PROOF + "  x;\n"),
    (WS + "\\(assume\\)" + WS, " assume A [H];"), (WS0, " \n\t"), (WS0, " a "),
    # strings with other characters than ASCII's are matched by their bytes
    ("⇒", "a ⇒ b ⇒ c"), ("[^;]*;", "∀x. P ⇒ Q; rest"),
    (WS + "\\([^ \t\n]+\\)", " α⇒β x"), ("∧\\|∨", "p ∧ q ∨ r"),
]


def lit(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\t", "\\t") + '"'


ML = r'''(* Generated by tools/ocaml_ref/str_ref.py: lib/str.mbt against Str. *)
#load "str.cma";;
let count_groups pat =
  let n = ref 1 in
  for i = 0 to String.length pat - 2 do
    if pat.[i] = '\\' && pat.[i + 1] = '(' then incr n
  done;
  !n
let groups n s =
  String.concat ","
    (List.init n (fun i ->
         try "[" ^ String.escaped (Str.matched_group i s) ^ "]"
         with Not_found -> "-" | Invalid_argument _ -> "!"))
let show name f =
  Printf.printf "%s = %s\n" name
    (try f () with
     | Not_found -> "Not_found"
     | Invalid_argument m -> "Invalid_argument " ^ m
     | Failure m -> "Failure " ^ m)
let case pat s =
  Printf.printf "== %s on %s\n" (String.escaped pat) (String.escaped s);
  match (try Some (Str.regexp pat) with Failure m -> Printf.printf "regexp: Failure %s\n" m; None) with
  | None -> ()
  | Some re ->
      let ng = count_groups pat in
      show "match" (fun () ->
          if Str.string_match re s 0 then Printf.sprintf "%d %s" (Str.match_end ()) (groups ng s) else "no");
      show "forward" (fun () ->
          let p = Str.search_forward re s 0 in
          Printf.sprintf "%d-%d %s" p (Str.match_end ()) (groups ng s));
      show "backward" (fun () ->
          let p = Str.search_backward re s (String.length s) in
          Printf.sprintf "%d-%d %s" p (Str.match_end ()) (groups ng s));
      show "replace" (fun () -> String.escaped (Str.global_replace re "<\\0>" s));
      show "replace1" (fun () -> String.escaped (Str.global_replace re "[\\1\\\\\\n]" s));
      show "first" (fun () -> String.escaped (Str.replace_first re "#" s));
      show "split" (fun () -> String.escaped (String.concat "|" (Str.split re s)));;
'''

MBT = r'''// Generated by tools/ocaml_ref/str_ref.py: lib/str.mbt against OCaml's Str
// (tools/ocaml_ref/str_ref.ml, str_ref.expected).

///|
fn count_groups(pat : String) -> Int {
  let mut n = 1
  for i in 0..<(pat.length() - 1) {
    if pat[i].to_int() == '\\'.to_int() && pat[i + 1].to_int() == '('.to_int() {
      n += 1
    }
  }
  n
}

///|
fn groups(n : Int, s : String) -> String {
  let parts : Array[String] = []
  for i in 0..<n {
    let part = try {
      "[" + @lib.string_escaped(@lib.str_matched_group(i.to_int64(), s)) + "]"
    } catch {
      @lib.NotFound => "-"
      _ => "!"
    }
    parts.push(part)
  }
  parts.join(",")
}

///|
fn show(out : StringBuilder, name : String, f : () -> String raise) -> Unit {
  let r = try {
    f()
  } catch {
    @lib.NotFound => "Not_found"
    @num.InvalidArgument(m) => "Invalid_argument " + m
    Failure(m) => "Failure " + m
    e => e.to_string()
  }
  out.write_string("\{name} = \{r}\n")
}

///|
fn case(out : StringBuilder, pat : String, s : String) -> Unit {
  out.write_string(
    "== \{@lib.string_escaped(pat)} on \{@lib.string_escaped(s)}\n",
  )
  let re = @lib.str_regexp(pat) catch {
    Failure(m) => {
      out.write_string("regexp: Failure \{m}\n")
      return
    }
    e => {
      out.write_string("regexp: \{e}\n")
      return
    }
  }
  let ng = count_groups(pat)
  show(out, "match", () => {
    if @lib.str_string_match(re, s, 0L) {
      "\{@lib.str_match_end(())} \{groups(ng, s)}"
    } else {
      "no"
    }
  })
  show(out, "forward", () => {
    let p = @lib.str_search_forward(re, s, 0L)
    "\{p}-\{@lib.str_match_end(())} \{groups(ng, s)}"
  })
  show(out, "backward", () => {
    let p = @lib.str_search_backward(
      re,
      s,
      @lib.string_length(s).to_int64(),
    )
    "\{p}-\{@lib.str_match_end(())} \{groups(ng, s)}"
  })
  show(out, "replace", () => {
    @lib.string_escaped(@lib.str_global_replace(re, "<\\0>", s))
  })
  show(out, "replace1", () => {
    @lib.string_escaped(@lib.str_global_replace(re, "[\\1\\\\\\n]", s))
  })
  show(out, "first", () => {
    @lib.string_escaped(@lib.str_replace_first(re, "#", s))
  })
  show(out, "split", () => {
    @lib.string_escaped(@lib.str_split(re, s).to_array().join("|"))
  })
}

///|
test "Str matches OCaml's" {
  let out = StringBuilder::new()
CASES
  inspect(
    out.to_string(),
    content=(
EXPECTED
    ),
  )
}
'''


def main():
    ml = os.path.join(REF, "str_ref.ml")
    open(ml, "w").write(ML + "".join(f"case {lit(p)} {lit(s)};;\n" for p, s in CASES))
    out = subprocess.run(["sh", "-c", 'eval "$(opam env --switch="${HOL_LIGHT_SWITCH:-hol-light}" --set-switch 2>/dev/null)"; '
                          f"ocaml {ml}"], capture_output=True, text=True, check=True).stdout
    open(os.path.join(REF, "str_ref.expected"), "w").write(out)
    cases = "".join(f"  case(out, {lit(p)}, {lit(s)})\n" for p, s in CASES).rstrip("\n")
    expected = "".join(f"      #|{line}\n" for line in out.splitlines()) + "      #|"
    open(os.path.join(ROOT, "lib", "str_ref_test.mbt"), "w").write(
        MBT.replace("CASES", cases).replace("EXPECTED", expected))
    print(f"{len(CASES)} cases, {len(out.splitlines())} lines")


main()
