#!/usr/bin/env python3
"""Write the standard differential test for a translated theory file.

usage: theory_test.py <name>

Writes tools/ocaml_ref/<name>_ref.ml (loading everything before <name>.ml
in hol.ml's order, then <name>.ml with its quotation trace, its theorem
list and the types/constants/definitions/counters) and the matching
<name>/<name>_ref_test.mbt; extra checks can be appended to both between
the EXTRA markers. Then: gen_theorems_test.py <name>, run.sh, embed_golden.py.
"""
import sys

ORDER = ["bool", "drule", "tactics", "itab", "simp", "theorems", "ind_defs", "class",
         "trivia", "canon", "meson", "firstorder", "metis", "thecops", "quot", "impconv",
         "pair", "compute", "nums", "recursion", "arith", "wf", "calc_num", "normalizer",
         "grobner", "ind_types", "lists", "realax", "calc_int", "realarith", "real",
         "calc_rat", "int", "sets", "iterate", "cart", "define"]
# theories whose load output the MoonBit side replays (begin_theory names)
THEORIES = [t for t in ORDER if t not in ("bool", "drule", "tactics", "itab")]

name = sys.argv[1]
i = ORDER.index(name)
before = ORDER[:i]
ml = [f"(* Load-fidelity test for {name}.ml (translated by tools/translator). Keep\n"
      f"   in sync with {name}/{name}_ref_test.mbt (the theorem list part is\n"
      "   generated by tools/ocaml_ref/gen_theorems_test.py). *)\n"]
ml += [f'#use "{f}.ml";;\n' for f in before]
ml += ["start_trace ();;\n", f'#use "{name}.ml";;\n', f'show_trace "{name}";;\n',
       "(* BEGIN generated theorem list *)\n(* END generated theorem list *)\n",
       "let tm s = parse_term s;;\n",
       'attempt "types" (fun () -> String.concat " " (map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;\n',
       'attempt "constants" (fun () -> String.concat " " (map fst (constants())));;\n',
       'attempt "definitions" (fun () -> string_of_int (length (definitions())));;\n',
       "(* BEGIN EXTRA *)\n(* END EXTRA *)\n",
       'attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;\n',
       'attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;\n']
open(f"tools/ocaml_ref/{name}_ref.ml", "w").write("".join(ml))
ths = THEORIES[:THEORIES.index(name) + 1]
quoted = ", ".join(f'"{t}"' for t in ths)
mbt = f"""// Load-fidelity test for {name}.ml: replays tools/ocaml_ref/{name}_ref.ml
// (keep in sync; the theorem list part is generated by
// tools/ocaml_ref/gen_theorems_test.py).

///|
using @testkit {{stm, sthm}}

///|
test "{name} matches {name}.ml" {{
  let log = @testkit.Log::new()
  log.capture_reports()
  for th in [{quoted}] {{
    log.show_theory_output(th)
  }}
  log.show_theory_trace("{name}")
  log.capture_stdout()
  // BEGIN generated theorem list
  // END generated theorem list
  let tm = @parser.parse_term
  log.attempt("types", () => {{
    @kernel.types().map(p => p.0 + "/" + p.1.to_string()).to_array().join(" ")
  }})
  log.attempt("constants", () => {{
    @kernel.constants().map(c => c.0).to_array().join(" ")
  }})
  log.attempt("definitions", () => @kernel.definitions().length().to_string())
  // BEGIN EXTRA
  // END EXTRA
  log.attempt("counter_tyvar", () => stm(tm("zz_counter")))
  log.attempt("counter_genvar", () => stm(@basics.genvar(@kernel.bool_ty)))
  inspect(@testkit.normalize_times(log.contents()))
}}
"""
open(f"{name}/{name}_ref_test.mbt", "w").write(mbt)
