(* Load-fidelity test for Tutorial/Tactics_and_tacticals.ml (translated by tools/translator). Keep
   in sync with tutorial/Tactics_and_tacticals/Tactics_and_tacticals_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
start_trace ();;
#use "Tutorial/Tactics_and_tacticals.ml";;
show_trace "Tutorial/Tactics_and_tacticals";;
(* BEGIN generated theorem list *)
attempt "trivial" (fun () -> sthm trivial);;
attempt "SUM_OF_NUMBERS" (fun () -> sthm SUM_OF_NUMBERS);;
attempt "SUM_OF_SQUARES" (fun () -> sthm SUM_OF_SQUARES);;
attempt "SUM_OF_CUBES" (fun () -> sthm SUM_OF_CUBES);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
