(* Load-fidelity test for Tutorial/Embedding_of_logics_shallow.ml (translated by tools/translator). Keep
   in sync with tutorial/Embedding_of_logics_shallow/Embedding_of_logics_shallow_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
start_trace ();;
#use "Tutorial/Embedding_of_logics_shallow.ml";;
show_trace "Tutorial/Embedding_of_logics_shallow";;
(* BEGIN generated theorem list *)
attempt "false_def" (fun () -> sthm false_def);;
attempt "true_def" (fun () -> sthm true_def);;
attempt "not_def" (fun () -> sthm not_def);;
attempt "and_def" (fun () -> sthm and_def);;
attempt "or_def" (fun () -> sthm or_def);;
attempt "imp_def" (fun () -> sthm imp_def);;
attempt "iff_def" (fun () -> sthm iff_def);;
attempt "forever" (fun () -> sthm forever);;
attempt "sometime" (fun () -> sthm sometime);;
attempt "next" (fun () -> sthm next);;
attempt "until" (fun () -> sthm until);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
