(* Load-fidelity test for Tutorial/Number_theory.ml (translated by tools/translator). Keep
   in sync with tutorial/Number_theory/Number_theory_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "Library/prime.ml";;
#use "Library/iter.ml";;
#use "Library/pocklington.ml";;
#use "Library/binomial.ml";;
start_trace ();;
#use "Tutorial/Number_theory.ml";;
show_trace "Tutorial/Number_theory";;
(* BEGIN generated theorem list *)
attempt "CONG_TRIVIAL" (fun () -> sthm CONG_TRIVIAL);;
attempt "DIVIDES_FACT_PRIME" (fun () -> sthm DIVIDES_FACT_PRIME);;
attempt "DIVIDES_BINOM_PRIME" (fun () -> sthm DIVIDES_BINOM_PRIME);;
attempt "DIVIDES_NSUM" (fun () -> sthm DIVIDES_NSUM);;
attempt "FLT_LEMMA" (fun () -> sthm FLT_LEMMA);;
attempt "FERMAT_LITTLE" (fun () -> sthm FERMAT_LITTLE);;
attempt "FERMAT_LITTLE_COPRIME" (fun () -> sthm FERMAT_LITTLE_COPRIME);;
attempt "FERMAT_LITTLE_VARIANT" (fun () -> sthm FERMAT_LITTLE_VARIANT);;
attempt "RSA" (fun () -> sthm RSA);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
