(* Load-fidelity test for Tutorial/Recursive_definitions.ml (translated by tools/translator). Keep
   in sync with tutorial/Recursive_definitions/Recursive_definitions_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
start_trace ();;
#use "Tutorial/Recursive_definitions.ml";;
show_trace "Tutorial/Recursive_definitions";;
(* BEGIN generated theorem list *)
attempt "fib" (fun () -> sthm fib);;
attempt "fib2" (fun () -> sthm fib2);;
attempt "halve" (fun () -> sthm halve);;
attempt "unknown" (fun () -> sthm unknown);;
attempt "fusc_def" (fun () -> sthm fusc_def);;
attempt "fusc" (fun () -> sthm fusc);;
attempt "binom" (fun () -> sthm binom);;
attempt "BINOM_LT" (fun () -> sthm BINOM_LT);;
attempt "BINOM_REFL" (fun () -> sthm BINOM_REFL);;
attempt "BINOM_FACT" (fun () -> sthm BINOM_FACT);;
attempt "BINOMIAL_THEOREM" (fun () -> sthm BINOMIAL_THEOREM);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
