(* Load-fidelity test for Tutorial/HOL_as_a_functional_programming_language.ml (translated by tools/translator). Keep
   in sync with tutorial/HOL_as_a_functional_programming_language/HOL_as_a_functional_programming_language_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
start_trace ();;
#use "Tutorial/HOL_as_a_functional_programming_language.ml";;
show_trace "Tutorial/HOL_as_a_functional_programming_language";;
(* BEGIN generated theorem list *)
attempt "ite_INDUCT" (fun () -> sthm ite_INDUCT);;
attempt "ite_RECURSION" (fun () -> sthm ite_RECURSION);;
attempt "eth" (fun () -> sthm eth);;
attempt "sizeof" (fun () -> sthm sizeof);;
attempt "eth'" (fun () -> sthm eth');;
attempt "norm" (fun () -> sthm norm);;
attempt "SIZEOF_INDUCT" (fun () -> sthm SIZEOF_INDUCT);;
attempt "SIZEOF_NZ" (fun () -> sthm SIZEOF_NZ);;
attempt "ITE_INDUCT" (fun () -> sthm ITE_INDUCT);;
attempt "normalized" (fun () -> sthm normalized);;
attempt "NORMALIZED_NORM" (fun () -> sthm NORMALIZED_NORM);;
attempt "NORMALIZED_INDUCT" (fun () -> sthm NORMALIZED_INDUCT);;
attempt "holds" (fun () -> sthm holds);;
attempt "HOLDS_NORM" (fun () -> sthm HOLDS_NORM);;
attempt "taut" (fun () -> sthm taut);;
attempt "tautology" (fun () -> sthm tautology);;
attempt "NORMALIZED_TAUT" (fun () -> sthm NORMALIZED_TAUT);;
attempt "TAUTOLOGY" (fun () -> sthm TAUTOLOGY);;
attempt "HOLDS_BACK" (fun () -> sthm HOLDS_BACK);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
