(* Load-fidelity test for Tutorial/Inductive_definitions.ml (translated by tools/translator). Keep
   in sync with tutorial/Inductive_definitions/Inductive_definitions_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
#use "Library/rstc.ml";;
start_trace ();;
#use "Tutorial/Inductive_definitions.ml";;
show_trace "Tutorial/Inductive_definitions";;
(* BEGIN generated theorem list *)
attempt "move" (fun () -> sthm move);;
attempt "reachable_RULES" (fun () -> sthm reachable_RULES);;
attempt "reachable_INDUCT" (fun () -> sthm reachable_INDUCT);;
attempt "reachable_CASES" (fun () -> sthm reachable_CASES);;
attempt "oriented_area" (fun () -> sthm oriented_area);;
attempt "MOVE_INVARIANT" (fun () -> sthm MOVE_INVARIANT);;
attempt "REACHABLE_INVARIANT" (fun () -> sthm REACHABLE_INVARIANT);;
attempt "IMPOSSIBILITY_B" (fun () -> sthm IMPOSSIBILITY_B);;
attempt "init" (fun () -> sthm init);;
attempt "trans" (fun () -> sthm trans);;
attempt "mutex" (fun () -> sthm mutex);;
attempt "indinv" (fun () -> sthm indinv);;
attempt "INDUCTIVE_INVARIANT" (fun () -> sthm INDUCTIVE_INVARIANT);;
attempt "MUTEX" (fun () -> sthm MUTEX);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
