(* Load-fidelity test for Tutorial/Semantics_of_programming_languages_deep.ml (translated by tools/translator). Keep
   in sync with tutorial/Semantics_of_programming_languages_deep/Semantics_of_programming_languages_deep_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
start_trace ();;
#use "Tutorial/Semantics_of_programming_languages_deep.ml";;
show_trace "Tutorial/Semantics_of_programming_languages_deep";;
(* BEGIN generated theorem list *)
attempt "string_INDUCT" (fun () -> sthm string_INDUCT);;
attempt "string_RECURSION" (fun () -> sthm string_RECURSION);;
attempt "expression_INDUCT" (fun () -> sthm expression_INDUCT);;
attempt "expression_RECURSION" (fun () -> sthm expression_RECURSION);;
attempt "command_INDUCT" (fun () -> sthm command_INDUCT);;
attempt "command_RECURSION" (fun () -> sthm command_RECURSION);;
attempt "value" (fun () -> sthm value);;
attempt "sem_RULES" (fun () -> sthm sem_RULES);;
attempt "sem_INDUCT" (fun () -> sthm sem_INDUCT);;
attempt "sem_CASES" (fun () -> sthm sem_CASES);;
attempt "DETERMINISM" (fun () -> sthm DETERMINISM);;
attempt "wlp" (fun () -> sthm wlp);;
attempt "terminates" (fun () -> sthm terminates);;
attempt "wp" (fun () -> sthm wp);;
attempt "WP_TOTAL" (fun () -> sthm WP_TOTAL);;
attempt "WP_MONOTONIC" (fun () -> sthm WP_MONOTONIC);;
attempt "WP_DISJUNCTIVE" (fun () -> sthm WP_DISJUNCTIVE);;
attempt "WP_SEQ" (fun () -> sthm WP_SEQ);;
attempt "correct" (fun () -> sthm correct);;
attempt "CORRECT_PRESTRENGTH" (fun () -> sthm CORRECT_PRESTRENGTH);;
attempt "CORRECT_POSTWEAK" (fun () -> sthm CORRECT_POSTWEAK);;
attempt "CORRECT_SEQ" (fun () -> sthm CORRECT_SEQ);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
