(* Load-fidelity test for Tutorial/Inductive_datatypes.ml (translated by tools/translator). Keep
   in sync with tutorial/Inductive_datatypes/Inductive_datatypes_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
start_trace ();;
#use "Tutorial/Inductive_datatypes.ml";;
show_trace "Tutorial/Inductive_datatypes";;
(* BEGIN generated theorem list *)
attempt "line_INDUCT" (fun () -> sthm line_INDUCT);;
attempt "line_RECURSION" (fun () -> sthm line_RECURSION);;
attempt "point_INDUCT" (fun () -> sthm point_INDUCT);;
attempt "point_RECURSION" (fun () -> sthm point_RECURSION);;
attempt "ON" (fun () -> sthm ON);;
attempt "ON_CLAUSES" (fun () -> sthm ON_CLAUSES);;
attempt "FORALL_POINT" (fun () -> sthm FORALL_POINT);;
attempt "FORALL_LINE" (fun () -> sthm FORALL_LINE);;
attempt "EXISTS_POINT" (fun () -> sthm EXISTS_POINT);;
attempt "EXISTS_LINE" (fun () -> sthm EXISTS_LINE);;
attempt "AXIOM_1" (fun () -> sthm AXIOM_1);;
attempt "AXIOM_2" (fun () -> sthm AXIOM_2);;
attempt "AXIOM_3" (fun () -> sthm AXIOM_3);;
attempt "AXIOM_4" (fun () -> sthm AXIOM_4);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
