(* Load-fidelity test for Tutorial/Embedding_of_logics_deep.ml (translated by tools/translator). Keep
   in sync with tutorial/Embedding_of_logics_deep/Embedding_of_logics_deep_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
#use "wf.ml";;
#use "calc_num.ml";;
#use "normalizer.ml";;
#use "grobner.ml";;
#use "ind_types.ml";;
#use "lists.ml";;
#use "realax.ml";;
#use "calc_int.ml";;
#use "realarith.ml";;
#use "real.ml";;
#use "calc_rat.ml";;
#use "int.ml";;
#use "sets.ml";;
#use "iterate.ml";;
#use "cart.ml";;
#use "define.ml";;
start_trace ();;
#use "Tutorial/Embedding_of_logics_deep.ml";;
show_trace "Tutorial/Embedding_of_logics_deep";;
(* BEGIN generated theorem list *)
attempt "string_INDUCT" (fun () -> sthm string_INDUCT);;
attempt "string_RECURSION" (fun () -> sthm string_RECURSION);;
attempt "form_INDUCT" (fun () -> sthm form_INDUCT);;
attempt "form_RECURSION" (fun () -> sthm form_RECURSION);;
attempt "holds" (fun () -> sthm holds);;
attempt "holds_in" (fun () -> sthm holds_in);;
attempt "valid" (fun () -> sthm valid);;
attempt "S4" (fun () -> sthm S4);;
attempt "LTL" (fun () -> sthm LTL);;
attempt "GL" (fun () -> sthm GL);;
attempt "TAUT_1" (fun () -> sthm TAUT_1);;
attempt "TAUT_2" (fun () -> sthm TAUT_2);;
attempt "TAUT_3" (fun () -> sthm TAUT_3);;
attempt "TAUT_4" (fun () -> sthm TAUT_4);;
attempt "TAUT_5" (fun () -> sthm TAUT_5);;
attempt "TAUT_6" (fun () -> sthm TAUT_6);;
attempt "HOLDS_FORALL_LEMMA" (fun () -> sthm HOLDS_FORALL_LEMMA);;
attempt "MODAL_REFL" (fun () -> sthm MODAL_REFL);;
attempt "MODAL_TRANS" (fun () -> sthm MODAL_TRANS);;
attempt "MODAL_SERIAL" (fun () -> sthm MODAL_SERIAL);;
attempt "MODAL_SYM" (fun () -> sthm MODAL_SYM);;
attempt "MODAL_WFTRANS" (fun () -> sthm MODAL_WFTRANS);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (List.map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (List.map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (List.length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
