(* Load-fidelity test for wf.ml (translated by tools/translator). Keep
   in sync with wf/wf_ref_test.mbt (the theorem list part is
   generated by tools/ocaml_ref/gen_theorems_test.py). *)
#use "bool.ml";;
#use "drule.ml";;
#use "tactics.ml";;
#use "itab.ml";;
#use "simp.ml";;
#use "theorems.ml";;
#use "ind_defs.ml";;
#use "class.ml";;
#use "trivia.ml";;
#use "canon.ml";;
#use "meson.ml";;
#use "firstorder.ml";;
#use "metis.ml";;
#use "thecops.ml";;
#use "quot.ml";;
#use "impconv.ml";;
#use "pair.ml";;
#use "compute.ml";;
#use "nums.ml";;
#use "recursion.ml";;
#use "arith.ml";;
start_trace ();;
#use "wf.ml";;
show_trace "wf";;
(* BEGIN generated theorem list *)
attempt "WF" (fun () -> sthm WF);;
attempt "WF_EQ" (fun () -> sthm WF_EQ);;
attempt "WF_IND" (fun () -> sthm WF_IND);;
attempt "WF_DCHAIN" (fun () -> sthm WF_DCHAIN);;
attempt "WF_DHAIN_TRANSITIVE" (fun () -> sthm WF_DHAIN_TRANSITIVE);;
attempt "WF_UREC" (fun () -> sthm WF_UREC);;
attempt "WF_UREC_WF" (fun () -> sthm WF_UREC_WF);;
attempt "WF_REC_INVARIANT" (fun () -> sthm WF_REC_INVARIANT);;
attempt "WF_REC" (fun () -> sthm WF_REC);;
attempt "WF_REC_WF" (fun () -> sthm WF_REC_WF);;
attempt "WF_EREC" (fun () -> sthm WF_EREC);;
attempt "WF_REC_EXISTS" (fun () -> sthm WF_REC_EXISTS);;
attempt "WF_SUBSET" (fun () -> sthm WF_SUBSET);;
attempt "WF_RESTRICT" (fun () -> sthm WF_RESTRICT);;
attempt "WF_MEASURE_GEN" (fun () -> sthm WF_MEASURE_GEN);;
attempt "WF_LEX_DEPENDENT" (fun () -> sthm WF_LEX_DEPENDENT);;
attempt "WF_LEX" (fun () -> sthm WF_LEX);;
attempt "WF_POINTWISE" (fun () -> sthm WF_POINTWISE);;
attempt "WF_num" (fun () -> sthm WF_num);;
attempt "WF_REC_num" (fun () -> sthm WF_REC_num);;
attempt "MEASURE" (fun () -> sthm MEASURE);;
attempt "WF_MEASURE" (fun () -> sthm WF_MEASURE);;
attempt "MEASURE_LE" (fun () -> sthm MEASURE_LE);;
attempt "WF_ANTISYM" (fun () -> sthm WF_ANTISYM);;
attempt "WF_REFL" (fun () -> sthm WF_REFL);;
attempt "WF_FALSE" (fun () -> sthm WF_FALSE);;
attempt "MINIMAL_BAD_SEQUENCE" (fun () -> sthm MINIMAL_BAD_SEQUENCE);;
attempt "WF_REC_TAIL" (fun () -> sthm WF_REC_TAIL);;
attempt "WF_REC_TAIL_GENERAL" (fun () -> sthm WF_REC_TAIL_GENERAL);;
(* END generated theorem list *)
let tm s = parse_term s;;
attempt "types" (fun () -> String.concat " " (map (fun (s,n) -> s ^ "/" ^ string_of_int n) (types())));;
attempt "constants" (fun () -> String.concat " " (map fst (constants())));;
attempt "definitions" (fun () -> string_of_int (length (definitions())));;
(* BEGIN EXTRA *)
(* END EXTRA *)
attempt "counter_tyvar" (fun () -> stm (tm "zz_counter"));;
attempt "counter_genvar" (fun () -> stm (genvar bool_ty));;
